### PR TITLE
Remove servant-blaze and servant-lucid

### PR DESCRIPTION
**Pull request by phadej**
Moved to
- https://github.com/haskell-servant/servant-blaze
- https://github.com/haskell-servant/servant-lucid

### CODE REVIEW

**Comment by jkarni** [comment]
Looks like the `source-repo` and `bug-reports` in those repos haven't been updated. But otherwise LGTM.

**Comment by phadej** [comment]
@jkarni will update. And add some `README.md` as well

**Comment by phadej** [comment]
ping @jkarni, I update the repositories

**Comment by alpmestan** [comment]
I'm glad we're making the main repo a bit smaller. LGTM.

**Comment by phadej** [comment]
bump

**Comment by soenkehahn** [comment]
@phadej: Merged, thanks a lot!

**Pull request merged**
