### PR TITLE
Add changelog to be included on hackage

### PR DESCRIPTION
**Pull request by wiz**

### CODE REVIEW

**Comment by kosmikus** [comment]
I think this is good. But shouldn't it be done for all packages?

**Comment by kosmikus** [comment]
Actually, `servant-client` seems to be the only other package where it's missing so far ...

**Comment by kosmikus** [comment]
Both the cabal files actually already have an `extra-source-files` field. Could you please join these up, and also add the `README`, just as it is done for `servant-server`? Thanks.

**Comment by wiz** [comment]
Sent cleaner PR in #475. Github online editor - not even once! :worried:

**Pull request closed without merging**
