### PR TITLE
Allow resourcet-1.3 in servant-server and servant-conduit

### PR DESCRIPTION
**Pull request by tchoutri**
This PR allows for resourcet-1.3 in servant-server and servant-conduit

### CODE REVIEW

**Comment by shlevy** [comment]
Anything blocking this?

**Comment by tchoutri** [comment]
@shlevy nah I think we should be good once the CI passes.

**Comment by shlevy** [comment]
Can we get a release/revision with this?

**Comment by michaelpj** [comment]
gentle ping

**Pull request merged**
