### PR TITLE
Replace () with NoContent

### LINKED ISSUE #531: A lot of places still use () instead of NoContent
Changing `()` to `NoContent` in ComprhensiveAPI breakes pretty much everything =) 

We should be consistent and destroy the presence of `()` in my opinion. As docs are now unclear on which one to use.

### PR DESCRIPTION
**Pull request by arianvp**
Fixes #531 .

### CODE REVIEW

**Comment by arianvp** [comment]
Reasoning:

In servant-server we advice to use `NoContent` instead of `()` but all the other code was still using `()`. Basically. a 0.7 API could not use any other library but `servant-server`.  This PR should fix this.

@haskell-servant/maintainers could someone take a good look at this if I changed this correctly?

**Comment by soenkehahn** [comment]
LGTM. It's of course hard to tell whether you managed to replace every occurrence of `()` as a return type. Did you do some grepping?

And many thanks for fixing this!

**Comment by arianvp** [comment]
I've grepped and I think we're Okay.

**Comment by arianvp** [comment]
Also. this should probably be added released with 0.8 as it's a breaking API change.

**Comment by soenkehahn** [comment]
Again LGTM. Do you want to merge, @arianvp?

**Comment by arianvp** [comment]
LGTM

**Comment by arianvp** [comment]
@soenkehahn I squashed the commits

**Comment by jkarni** [comment]
LGTM

**Pull request merged**
