### PR TITLE
.travis.yml: use Ubuntu 16.04

### PR DESCRIPTION
**Pull request by vaibhavsagar**

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
Ideally this would be part of the `.travis.yml` that https://github.com/haskell-CI/haskell-ci generates.

**Comment by phadej** [comment]
@vaibhavsagar hacking on `haskell-ci` isn't that hard. I can help you there. (Yes, I'm sucking you down the rabbit hole).

**Comment by vaibhavsagar** [comment]
Can we merge this first, so that https://github.com/haskell-servant/servant/pull/1018 can proceed :smile:?

**Comment by phadej** [comment]
Well, I'd rather not, e.g. #1117 regenerates `.travis.yml` too. I use `haskell-ci` surprisingly a lot for `servant` repository (particularly managing cookbook recipes `allow-newer` etc.). And manual editing is not fun.

**Comment by vaibhavsagar** [comment]
Okay, I made a PR at https://github.com/haskell-CI/haskell-ci/pull/201.

**Comment by vaibhavsagar** [comment]
I just checked, and the `.travis.yml` in this PR matches the one generated by the latest `haskell-ci`.

**Comment by vaibhavsagar** [comment]
@phadej anything further I need to do here?

**Comment by vaibhavsagar** [comment]
Thanks!

**Pull request merged**
