### PR TITLE
Bump aeson version.

### PR DESCRIPTION
**Pull request by ondrap**
Solves #374 for the 0.4 branch.

### CODE REVIEW

**Comment by phadej** [comment]
note: if new `0.4` release will be made, `base` bounds have to be adjusted. See https://github.com/haskell-servant/servant/issues/384

**Comment by jkarni** [comment]
Thanks!

**Comment by jkarni** [comment]
@phadej why do the bounds for `base` have to be adjusted? If possible, I'd rather release with this change and then bump the bounds for `base` when we have CI setup.

**Comment by phadej** [comment]
@jkarni I don't remember the exact error-messages. IIRC it was related to the need for `UndecidableSuperClasses`

**Comment by fizruk** [comment]
@phadej I think `UndecidableSuperClasses` were needed for `servant-swagger`'s [`Every`](http://hackage.haskell.org/package/servant-swagger-1.0.3/docs/Servant-Swagger-Internal-TypeLevel-Every.html).

**Comment by phadej** [comment]
for the record:
```
[ 5 of 18] Compiling Servant.API.ContentTypes ( src/Servant/API/ContentTypes.hs, dist/build/Servant/API/ContentTypes.o )

src/Servant/API/ContentTypes.hs:199:1: error:
    • Potential superclass cycle for ‘AllCTUnrender’
        one of whose superclass constraints is headed by a type family:
          ‘IsNonEmpty list’
      Use UndecidableSuperClasses to accept this
    • In the class declaration for ‘AllCTUnrender’
```

**Pull request merged**
