### PR TITLE
Document servant-foreign

### PR DESCRIPTION
**Pull request by Profpatsch**
I spend some considerable time reverse engineering the module, so I
thought I’d write the documentation I would have liked to see.

The strategy here is that a user not necessarily has insight into how
servant works internally, or even how to write complex servant routes,
they just want to generate a list of endpoints and convert the `Req`
type into e.g. generated code in $language. Thus, they need to know
the semantics of all fields of Req, how they interact and how they
relate to a plain http route.

I made sure every `f` is replaced with `ftype`, so we have one
conventional way of referring to the foreign type argument everywhere.

Some enums are not set at all, they are marked as such.

`_reqBodyContentType` introduces a major restriction of the module, so
that is mentioned in the documentation for now, until the time it will
be fixed.

A few TODO’s describe places where types don’t make sense but would
introduce API-breaking changes, so these should probably be
simplified,
but bundled in one go.

### CODE REVIEW

**Comment by Profpatsch** [comment]
screenshot

**Comment by Profpatsch** [comment]
CI took … 4 hours to run and is mostly green, the checks that aren’t don’t show any errors. I don’t even know‽

**Comment by Profpatsch** [comment]
cc @arianvp

**Comment by arianvp** [comment]
Travis is extorting us for money unfortunately. So CI is completely unusable and unreliable until we give them money I don't have. There's a ticket to migrate away but I haven't found the time yet. https://github.com/haskell-servant/servant/issues/1353

**Comment by Profpatsch** [comment]
> Travis is extorting us for money unfortunately.

yeah, Travis has been bought by some company trying to wring as much money out of it as possible before closing down.

**Review by arianvp — APPROVED** [review]

**Comment by Profpatsch** [comment]
Can we merge this? Do we have to restart the travis builds?

I’d also appreciate a patch release so that people can see the new docs.

**Comment by akhesaCaro** [comment]
Hi Profpatsch, 

Thanks for your contribution. The CI has been fixed, could you rebase your branch to see if it passes the CI checks?

**Comment by Profpatsch** [comment]
rebased. thx

**Comment by Profpatsch** [comment]
@akhesaCaro Since this is a nontrivial UX improvement, can I ask for a point release?

**Comment by akhesaCaro** [comment]
I am sorry @Profpatsch, but we must ask @arianvp , I don't have the credentials on Hackage.

**Pull request merged**
