### PR TITLE
Support aeson-1.1

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
travis breakage seems due some test-deps, will check next week

**Comment by phadej** [comment]
green!

**Comment by alpmestan** [comment]
LGTM. I assume the extra packages that got removed went into newer stackage snapshots?

Any objection, anyone?

**Comment by phadej** [comment]
Yes packages removed have same or newer versions in new stackage snapshot. season-1.1 breaking change is related to how json is parsed, so doesn't affect servant as such. hspec-wai change is the same as in servant-mock

**Pull request merged**
