### PR TITLE
Add --max-backjumps to .travis.yml

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
```
Configuring library for warp-3.2.13..
Preprocessing library for warp-3.2.13..
Building library for warp-3.2.13..
Network/Wai/Handler/Warp/Response.hs:45:8:
    Could not find module ‘Data.Streaming.Blaze’
    Perhaps you meant
      Data.Streaming.Zlib (from streaming-commons-0.2.0.0)
      Data.Streaming.Text (from streaming-commons-0.2.0.0)
    Use -v to see a list of the files searched for.
cabal: Failed to build warp-3.2.13 (which is required by test:spec from
```

**Comment by jkarni** [comment]
Yeah, I started seeing this yesterday too, after a `cabal update`. Looks like a new version of `streaming-commons` was released without the module, and I guess later versions of `warp` don't use it?

I'm :+1: on this, though I've been wondering, what's the usual way of making `cabal`'s life easier (without increasing `max-backjumps`)? Is it to just have fewer dependencies and narrower version ranges?

**Comment by phadej** [comment]
In fact in this case also `--reorder-goals` helps solver to find a valid install plan.

**Comment by jkarni** [comment]
Opened an issue [here](https://github.com/yesodweb/wai/issues/678).

**Pull request merged**
