### PR TITLE
Delayed cleanup ioref tests

### PR DESCRIPTION
**Pull request by phadej**
Rebase of #622, with tests changed to use `IORef`

### CODE REVIEW

**Comment by phadej** [comment]
I'm ok with merging this, and then rewriting `DelayedIO` to use

```hs
newtype DelayedIO a = DelayedIO { runDelayedIO' :: ReaderT Request (ResourceT IO) (RouteResult a) }
```

opinions on this, @alpmestan, @jkarni?

**Comment by alpmestan** [comment]
There's some build failure to address (https://travis-ci.org/haskell-servant/servant/jobs/192826872#L393) -- for ghc 7.8. Other than that, LGTM.

**Comment by jkarni** [comment]
Why not just use `ResourceT` (and remove `CleanupRef`) from the start? It seems like we're just mimicking `ResourceT`s functionality, which, given how subtle these things can be (e.g., what happens in the presence of forks), is probably going to bite us.

**Comment by phadej** [comment]
@jkarni I'll make a refactor PR today.

**Pull request merged**
