### PR TITLE
Add basic auth to tutorial

### PR DESCRIPTION
**Pull request by jkarni**
Cherry picked from #407

### CODE REVIEW

**Comment by aaronlevin** [comment]
ah, thanks @jkarni . I was just sitting down to do this now. I owe you! Looks like this is passing and ready to merge.

**Comment by aaronlevin** [comment]
Since this is passing and since we've released and it'll be good to get this into the documentation, I'm going to merge this.

**Comment by soenkehahn** [comment]
The `Authentication.lhs` is not mentioned in any index file and therefore doesn't show up in the table of contents.

**Comment by aaronlevin** [comment]
I noticed this right after I merged. Trying to build the docs on NixOS has
been.... An experience (not your fault, but Nix's)

On Monday, 21 March 2016, Sönke Hahn <notifications@github.com> wrote:

> The Authentication.lhs is not mentioned in any index file and therefore
> doesn't show up in the table of contents.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/haskell-servant/servant/pull/416#issuecomment-199181432>
>


-- 
Aaron Levin / Weird Canada
www.aaronlevin.ca / www.weirdcanada.com

**Pull request merged**
