### PR TITLE
servant-client: Hide HttpException by wrapping it in SomeException

### PR DESCRIPTION
**Pull request by christian-marie**
This is what I meant by using SomeException

### CODE REVIEW

**Comment by alpmestan** [comment]
I'm fine with this change personally, although you can't do much with `SomeException` except show it. @jkarni ?

**Comment by christian-marie** [comment]
Well you can point ```fromException :: SomeException -> Maybe e``` at it, right?

I agree that if you could only show it there's no benefit.

**Comment by christian-marie** [comment]
I should write a test that shows this, I'll find some time today.

**Comment by christian-marie** [comment]
Didn't get around to this today, nor does it look like I will soon.

**Comment by christian-marie** [comment]
@jkarni?

**Comment by jkarni** [comment]
LGTM

**Pull request merged**
