### PR TITLE
Re-export Application.

### LINKED ISSUE #462: Re-export `Application` from `Servant` and `Servant.Server`
Since it's the result type of `serve`, I think this would make sense.

### PR DESCRIPTION
**Pull request by jkarni**
Fixes #462

### CODE REVIEW

**Comment by soenkehahn** [comment]
It's a bit buried in the discussions there (#NoMissionCreep), but #462 was about re-exporting `Application` from both `Servant` and `Servant.Server`. So this doesn't fully fix #462.

Still LGTM and could be merged as is (#NoMissionCreep).

**Comment by jkarni** [comment]
Hm, why `Servant.Server` too? My intuition was the `Servant` was where all of the not-directly-`servant-server` stuff got exported.

**Comment by soenkehahn** [comment]
My reasoning was that every module that exports `serve` should also re-export `Application`, because it's its return type.

**Comment by jkarni** [comment]
Done.

**Comment by alpmestan** [comment]
👍

**Pull request merged**
