### PR TITLE
Remove matrix

### PR DESCRIPTION
**Pull request by jkarni**

### CODE REVIEW

**Comment by jkarni** [comment]
Still need to go through this more carefully myself, but there it is.

**Comment by kosmikus** [comment]
What's the history here? Why are we doing this? I'm not overly fond of matrix parameters myself, but I haven't seen a discussion or decision to actually remove them.

**Comment by alpmestan** [comment]
https://github.com/haskell-servant/servant/issues/113 ?

**Comment by alpmestan** [comment]
What's not in the issue I linked to has mostly been discussed on IRC.

**Comment by kosmikus** [comment]
@alpmestan Hmm, perhaps I'm misunderstanding. That issue seems to propose a refactoring, whereas the title of this PR looks like it's aiming at removal. Can you clarify?

**Comment by alpmestan** [comment]
Yeah sorry, my answer was a bit too succint.

The idea is that the current matrix param code has got a few problems and incurs a runtime cost on *every single request*. Taking care of that requires some work and nobody but @dlarsson seems to be willing to take care of it, except that Daniel has been quite busy. The idea is to remove `MatrixParam`s until someone can nicely integrate them with everything else without the current problems.

If you're opposed to removing them and/or want to "fix" the current issues, now would be a good time to let your voice be heard =)

**Comment by kosmikus** [comment]
I'm not opposed to removing them.

**Comment by dlarsson** [comment]
I've started working on it, but yes, I'm not able to spend too much time on
it at the moment. Hopefully we can get them back in when I have a fix

2015-10-13 11:39 GMT+02:00 Andres Löh <notifications@github.com>:

**Comment by jkarni** [comment]
@dlarsson Cool - it'd definitely be better to have them. I think the litmus test for correctness here is that implementing them shouldn't require changing the core functions (i.e., it should in theory be possible to have them defined in a separate library).

**Comment by alpmestan** [comment]
LGTM.

**Comment by dmjio** [comment]
:+1:

**Pull request merged**
