### PR TITLE
Add RawM combinator

### LINKED ISSUE #1544: How to use custom Monad with wai's `Application`?
Say, you have an API built according to https://docs.servant.dev/en/stable/cookbook/using-custom-monad/UsingCustomMonad.html

Now you additionally have a `Raw` endpoint and want access to the ReaderT environment in the handler, which now is of type `Application` and not `Handler`.

Whatever I tried, I could not make it work (of course, I can pass the environment explicitly to the `server` function so I can just `runReaderT`, but that's not the "using custom monad" approach).

Example code:

```hs
{-# LANGUAGE DataKinds                  #-}
{-# LANGUAGE FlexibleContexts           #-}
{-# LANGUAGE OverloadedStrings          #-}
{-# LANGUAGE TypeOperators              #-}
{-# LANGUAGE RankNTypes                 #-}
{-# LANGUAGE ScopedTypeVariables        #-}

module Main where

import Control.Concurrent.Chan
import Control.Monad.IO.Class
import Data.Proxy
import Servant.API
import Servant.Server
import Network.Wai
import Control.Monad.Trans.Reader
import Network.Wai.Handler.Warp ( run )
import Network.Wai.Internal


type AppM = ReaderT AppState Handler

type WaiApplicationM = Request -> (Response -> IO ResponseReceived) -> AppM ResponseReceived

data AppState = AppState (Chan Int)

type API = LOL :<|> WAI

type WAI = "wai" :> Raw
type LOL = "lol" :> Get '[JSON] [Int]

api :: Proxy API
api = Proxy

server :: ServerT API AppM
server = lol :<|> (Tagged waiHandler :: Tagged AppM WaiApplicationM)
  where
    waiHandler :: WaiApplicationM
    waiHandler = \_ _ -> pure ResponseReceived

    lol :: AppM [Int]
    lol = do
      liftIO $ putStrLn "lol"
      return [1]

app :: Application
app = \req resp -> do
  c <- newChan
  serve api (hoistServer api (nt (AppState c)) $ server) req resp
 where
  nt :: AppState -> AppM a -> Handler a
  nt s x = flip runReaderT s x   

main :: IO ()
main = run 8081 app
```

Error:

```
app/Main.hs:36:10: error:
    • Couldn't match type ‘ReaderT AppState Handler ResponseReceived’
                     with ‘IO ResponseReceived’
      Expected type: ServerT API AppM
        Actual type: AppM [Int] :<|> Tagged AppM WaiApplicationM
    • In the expression:
        lol :<|> (Tagged waiHandler :: Tagged AppM WaiApplicationM)
      In an equation for ‘server’:
          server
            = lol :<|> (Tagged waiHandler :: Tagged AppM WaiApplicationM)
            where
                waiHandler :: WaiApplicationM
                waiHandler = \ _ _ -> pure ResponseReceived
                lol :: AppM [Int]
                lol
                  = do liftIO $ putStrLn "lol"
                       ....
   |
36 | server = lol :<|> (Tagged waiHandler :: Tagged AppM WaiApplicationM)
```

### PR DESCRIPTION
**Pull request by gdeest**
The 'RawM' combinator is a variant of 'Raw' that lets users access the monadic context of the server.

The handler must produce a WAI Response, like Raw.

Closes #1544 .

@hasufell may I have your input on this PR ?

### CODE REVIEW

**Comment by hasufell** [comment]
Thanks, I'll test this version with my code in a while.

**Comment by hasufell** [comment]
I don't see how to use this with my use case. E.g.:

```hs
newtype AppM a = AppM { runAppM :: ReaderT AppState Handler a }

streamEvent :: Request -> (Response -> IO ResponseReceived) -> AppM ResponseReceived
streamEvent req resp = do
  AppState{..} <- ask
  chan <- liftIO getChanListener
  liftIO $ eventSourceAppChan chan req resp
```

I need access to the `resp :: Response -> IO ResponseReceived`, because `eventSourceAppChan` is a library function and needs it: https://hackage.haskell.org/package/wai-extra-3.1.8/docs/Network-Wai-EventSource.html#v:eventSourceAppChan

**Comment by gdeest** [comment]
Ok, it's easier to understand what you need with this example. Easy enough, I'll update the PR.

**Comment by gdeest** [comment]
@hasufell PTAL.

**Comment by hasufell** [comment]
> @hasufell PTAL.

This is usable for my purpose

**Comment by amesgen** [comment]
Just FTR as they don't seem to have been mentioned here and in the linked issue: There is another PR adding this (#1349), and also an existing package: https://github.com/cdepillabout/servant-rawm

**Comment by gdeest** [comment]
Indeed¸I totally missed it. The cabal files do not mention any upper-bound on servant package, so with some luck `servant-rawm` is already compatible with servant 0.19 and we can just close this PR.

**Comment by hasufell** [comment]
> Indeed¸I totally missed it. The cabal files do not mention any upper-bound on servant package, so with some luck `servant-rawm` is already compatible with servant 0.19 and we can just close this PR.

Wouldn't it be better to add it to servant? I feel another library will not integrate as well and may lag behind releases.

**Comment by amesgen** [comment]
> Wouldn't it be better to add it to servant? I feel another library will not integrate as well and may lag behind releases.

Seconding this, another reason from https://github.com/haskell-servant/servant/pull/1349#issuecomment-713175218

> In particular, it will make it easier to close https://github.com/cdepillabout/servant-rawm/issues/7, as servant-auth can provide the required instance out of the box (without having to write a servant-auth-rawm compat package).

**Comment by alpmestan** [comment]
That seems reasonable to me. We'll just want to make sure the docs are crystal clear about when a user should consider `Raw` vs `RawM` etc.

**Comment by gdeest** [comment]
I have opened an issue on the `servant-rawm` repository to discuss a potential merge.

**Comment by hasufell** [comment]
@gdeest I'm having trouble using this with servant-auth-server:

```
    • No instance for (Servant.Auth.Server.Internal.AddSetCookie.AddSetCookies
                         ('Servant.Auth.Server.Internal.AddSetCookie.S
                            ('Servant.Auth.Server.Internal.AddSetCookie.S
                               'Servant.Auth.Server.Internal.AddSetCookie.Z))
                         (Network.Wai.Internal.Request
                          -> (Network.Wai.Internal.Response
                              -> IO Network.Wai.Internal.ResponseReceived)
                          -> Handler Network.Wai.Internal.ResponseReceived)
                         (ServerT
                            (Servant.Auth.Server.Internal.AddSetCookie.AddSetCookieApi
                               (Servant.Auth.Server.Internal.AddSetCookie.AddSetCookieApi
                                  Servant.API.Raw.RawM))
                            Handler))
        arising from a use of ‘serveWithContext’
```

Although this patch is already applied https://github.com/haskell-servant/servant/pull/1531

**Comment by amesgen** [comment]
@hasufell That is the same issue as in https://github.com/cdepillabout/servant-rawm/issues/7, see the penultimate comment for a solution. Actually, it is one of the motivations I mentioned [above](https://github.com/haskell-servant/servant/pull/1551#issuecomment-1064110949) to merge this PR:

> In particular, it will make it easier to close https://github.com/cdepillabout/servant-rawm/issues/7, as servant-auth can provide the required instance out of the box (without having to write a servant-auth-rawm compat package).

**Comment by hasufell** [comment]
> @hasufell That is the same issue as in [cdepillabout/servant-rawm#7](https://github.com/cdepillabout/servant-rawm/issues/7), see the penultimate comment for a solution. Actually, it is one of the motivations I mentioned [above](https://github.com/haskell-servant/servant/pull/1551#issuecomment-1064110949) to merge this PR:
> 
> > In particular, it will make it easier to close [cdepillabout/servant-rawm#7](https://github.com/cdepillabout/servant-rawm/issues/7), as servant-auth can provide the required instance out of the box (without having to write a servant-auth-rawm compat package).

I tried something along the suggestions: https://github.com/cdepillabout/servant-rawm/issues/7#issuecomment-419611219

More specifically:

```hs
type instance AddSetCookieApi RawM = RawM

type ApplicationM m = Request -> (Response -> IO ResponseReceived) -> m ResponseReceived

instance
  AddSetCookies ('S n) (Tagged m (ApplicationM m)) (Tagged m (ApplicationM m)) where
  addSetCookies cookies r = Tagged $ \request respond ->
    unTagged r request $ respond . mapResponseHeaders (++ mkHeaders cookies)

instance
  (Functor m) =>
  AddSetCookies ('S n) (m (ApplicationM m)) (m (ApplicationM m)) where
  addSetCookies cookies = undefined
```

But it didn't work:

```hs
    • Couldn't match type ‘Network.Wai.Internal.ResponseReceived’
                     with ‘Servant.API.ResponseHeaders.Headers
                             '[Servant.API.Header.Header "Set-Cookie" SetCookie] cookied0’
        arising from a use of ‘serveWithContext’
```

**Comment by hasufell** [comment]
This seemed to work, although I have no idea what it does:

```hs
type instance AddSetCookieApi RawM = RawM

type ApplicationM m = Request -> (Response -> IO ResponseReceived) -> m ResponseReceived

instance
  AddSetCookies ('S n) (Tagged m (ApplicationM m)) (Tagged m (ApplicationM m)) where
  addSetCookies cookies r = Tagged $ \request respond ->
    unTagged r request $ respond . mapResponseHeaders (++ mkHeaders cookies)

instance (Functor m)
  => AddSetCookies ('S n) (m (ApplicationM m)) (m (ApplicationM m)) where
  addSetCookies cookies = fmap $ addSetCookies cookies

instance AddSetCookies ('S n) (ApplicationM m) (ApplicationM m) where
  addSetCookies cookies r request respond
    = r request $ respond . mapResponseHeaders (++ mkHeaders cookies)
```

**Comment by hasufell** [comment]
Going further, I tried to move the `Auth foo bar` to the outer part of the API, so I can match on it before the handlers, like it's done in this spec: https://github.com/haskell-servant/servant/blob/bd9151b9de579e98d14add3328933d155df25fc9/servant-auth/servant-auth-server/test/Servant/Auth/ServerSpec.hs#L405-L419

However, that presents me with more type foo:

```
    • Overlapping instances for Servant.Auth.Server.Internal.AddSetCookie.AddSetCookies
                                  ('Servant.Auth.Server.Internal.AddSetCookie.S
                                     ('Servant.Auth.Server.Internal.AddSetCookie.S
                                        'Servant.Auth.Server.Internal.AddSetCookie.Z))
                                  ((Network.Wai.Internal.Request
                                    -> (Network.Wai.Internal.Response
                                        -> IO Network.Wai.Internal.ResponseReceived)
                                    -> Handler Network.Wai.Internal.ResponseReceived)
                                   Servant.API.Alternative.:<|> (Text
                                                                 -> Maybe Int
                                                                 -> Network.Wai.Internal.Request
                                                                 -> (Network.Wai.Internal.Response
                                                                     -> IO
                                                                          Network.Wai.Internal.ResponseReceived)
                                                                 -> Handler
                                                                      Network.Wai.Internal.ResponseReceived))
                                  ((Network.Wai.Internal.Request
                                    -> (Network.Wai.Internal.Response
                                        -> IO Network.Wai.Internal.ResponseReceived)
                                    -> Handler Network.Wai.Internal.ResponseReceived)
                                   Servant.API.Alternative.:<|> (Text
                                                                 -> Maybe Int
                                                                 -> Network.Wai.Internal.Request
                                                                 -> (Network.Wai.Internal.Response
                                                                     -> IO
                                                                          Network.Wai.Internal.ResponseReceived)
                                                                 -> Handler
                                                                      Network.Wai.Internal.ResponseReceived))
        arising from a use of ‘serveWithContext’
      Matching instances:
        two instances involving out-of-scope types
        (use -fprint-potential-instances to see them all)
```

**Comment by hasufell** [comment]
It seems the culprit is: https://github.com/haskell-servant/servant/blob/1fba9dc6048cea6184964032b861b052cd54878c/servant-auth/servant-auth-server/src/Servant/Auth/Server/Internal/AddSetCookie.hs#L73-L76

I managed to make it compile by adding another very similar instance:

```hs
instance {-# OVERLAPS #-}
  (AddSetCookies ('S n) a a, AddSetCookies ('S n) b b)
  => AddSetCookies ('S n) (a :<|> b) (a :<|> b) where
  addSetCookies cookies (a :<|> b) = addSetCookies cookies a :<|> addSetCookies cookies b
```

The diff of both instances is:

```diff
@@ -71,8 +71,8 @@ instance {-# OVERLAPPABLE #-}
       Just cookie -> addHeader cookie <$> addSetCookies rest oldVal

 instance {-# OVERLAPS #-}
-  (AddSetCookies ('S n) a a', AddSetCookies ('S n) b b')
-  => AddSetCookies ('S n) (a :<|> b) (a' :<|> b') where
+  (AddSetCookies ('S n) a a, AddSetCookies ('S n) b b)
+  => AddSetCookies ('S n) (a :<|> b) (a :<|> b) where
   addSetCookies cookies (a :<|> b) = addSetCookies cookies a :<|> addSetCookies cookies b
```

I'm not sure if this is a correct fix though.

**Comment by mgajda** [comment]
Any progress towards get `RawM` or another way to get better monad hoisting?
Or are we going to stay with bespoke solutions for now?

**Review by tchoutri — APPROVED** [review]

**Comment by hasufell** [comment]
@tchoutri did you see the conversation about servant-auth-server and the mentioned issues?

**Comment by tchoutri** [comment]
Yes and we have to bump the priority of thinking about resolving this. :)

**Comment by jhrcek** [comment]
I haven't implemented this feature so don't take my word for it, but if you look at the type that your handler for RawM endpoint should be it is:

https://github.com/haskell-servant/servant/blob/c05a9e2c9947c77eb8d600954d4cb5e8c4e35e7c/servant-server/src/Servant/Server/Internal.hs#L665

Changing your example in this way makes it compile (though didn't check if it actually works).
```haskell
 rawEndpoint = \req respond -> do
            manager <- ask
            let application = waiProxyTo forwardRequest defaultOnExc manager
            liftIO $ application req respond
```

**Pull request merged**
