### PR TITLE
Allow http-media 0.7

### PR DESCRIPTION
**Pull request by felixonmars**

### CODE REVIEW

**Comment by phadej** [comment]
Have you tested it compiles and test passes? Our CI doesn't test against newest versions, if not added to `stack.yaml` explicitly as `extra-deps`?

**Comment by felixonmars** [comment]
Yes, and I have tried a few operations to make sure :P

**Comment by phadej** [comment]
Thanks, but

https://github.com/haskell-servant/servant/commit/70aae4c5c0a3d20d6209d338931ea4a30da33214

:(

**Comment by felixonmars** [comment]
Ah, I didn't package servant-client for Arch so I overlooked that part...

**Comment by phadej** [comment]
It's ok, next time make a change to `stack.yaml`, then Travis will do the job ;)

**Comment by felixonmars** [comment]
Got it, many thanks :P

**Pull request merged**
