### PR TITLE
Release

### PR DESCRIPTION
**Pull request by soenkehahn**
I'd like to release `0.7`.

cc: @haskell-servant/maintainers

### CODE REVIEW

**Comment by phadej** [comment]
Is there a way to see combined changelog, what are recent/post-0.6 breaking changes?

**Comment by kosmikus** [comment]
LGTM.

**Comment by soenkehahn** [comment]
@phadej: No, we only have individual changelogs in the projects. See also #472.

**Comment by soenkehahn** [comment]
@phadej: Or better: I don't know a good way. Probably you could come up with a clever github url or git shell command that would show the changes to the changelog files since `0.6.1`.

**Comment by aaronlevin** [comment]
:+1:

**Pull request merged**
