### PR TITLE
Add response headers.

### PR DESCRIPTION
**Pull request by jkarni**
Provides an easy way to add headers to responses:
```
type MyEndpoint = Get '[JSON] (Headers [Header "Location" Link] Int)

myEndpoint :: Server MyEndpoint
myEndpoint = return $ addHeader <somelink> 5
```

### CODE REVIEW

**Comment by jkarni** [comment]
Closes #28

**Comment by alpmestan** [comment]
Wonderful PR. Can I merge now?

**Comment by alpmestan** [comment]
This also fixes #25 and closes #27.

**Comment by alpmestan** [comment]
Also, are accompanying PRs for the other libraries coming too?

**Comment by jkarni** [comment]
Yeah, `servant-server` is already done (but of course failing till this gets merged). I'll add servant-client etc soon

**Pull request merged**
