### PR TITLE
Remove memoReqBody.

### LINKED ISSUE #356: Remove memoReqBody
Currently `memoReqBody` keeps the entire request body in memory. This was originally there because, prior to @kosmikus 's work, we *had* to backtrack requests against the API. We decided to keep it there because it makes the semantics of `ReqBody` somewhat nicer and we weren't sure how things would play out, but I think by now everyone agrees having the request in memory is not acceptable.

I think this should mean that bad bodies are `FailFatal`, so that if two `ReqBody`s occur as in:

```
type API = ReqBody '[JSON] Int :> Post ..
          :<|> ReqBody '[JSON] Bool :> Post ...
```

The second one never gets tried.

### PR DESCRIPTION
**Pull request by jkarni**
Fixes #356

### CODE REVIEW

**Comment by codedmart** [comment]
This LGTM, I am going to have a need for this soon.

**Comment by soenkehahn** [comment]
I think we should have test cases for:
- streaming working properly and
- an API with overlapping `ReqBody` routes (and the behavior we want for that).

Without that I'm not really convinced this is working.

**Comment by jkarni** [comment]
Added a test for 400 in overlapping bodies. This PR doesn't propose to add streaming - just to remove the memoized body - I'm not sure how to test streaming without implementing it.

**Comment by soenkehahn** [comment]
Very fair. LGTM.

**Pull request merged**
