### PR TITLE
Allow lens-5.3

### PR DESCRIPTION
**Pull request by ysangkok**
Tested using

    cabal build servant-docs servant-auth servant-foreign servant-swagger servant-auth-server servant-auth-swagger \
    -c 'lens>=5.3' --allow-newer=servant-multipart:lens,servant-openapi3:lens,insert-ordered-containers:lens,openapi3:lens,swagger2:lens,servant-js:lens

### CODE REVIEW

**Review by tchoutri — APPROVED** [review]

**Comment by maksbotan** [comment]
I will make revisions after we do QuickCheck, to avoid double work.

**Comment by ysangkok** [comment]
@maksbotan I have bumped QuickCheck now:

* https://github.com/haskell-servant/servant/pull/1761

So we should be ready to make bumps for lens?

**Comment by maksbotan** [comment]
Looks like that!

I'll make hackage revisions later this day.

Thank you for the contributions.

**Comment by maksbotan** [comment]
Done revisions. I hope I did not forget anything :)

**Comment by kokobd** [comment]
Could you please make a revision on [`servant-auth`](https://hackage.haskell.org/package/servant-auth) too?

**Comment by ysangkok** [comment]
@kokobd I think maksbotan has notifications turned off. But one way to get the bump done is to [ask on the trustee issues tracker](https://github.com/haskell-infra/hackage-trustees/issues).

**Pull request merged**
