### PR TITLE
Renamed `AtLeastOneFragment` type class to `AtMostOneFragment`

### PR DESCRIPTION
**Pull request by DavidMazarro**
Unless I'm misunderstanding the `FragmentUnique` type family, it's checking that there's **at most** one fragment in the API type. In that case, the `AtLeastOneFragment` name is not only confusing, but potentially misleading. This PR renames the type class to `AtMostOneFragment`.

In addition, I did some small changes to the documentation, I moved the explanation of the type class to the type class definition (previously the comment was under the `Verb` instance) and reworded it a bit.

### CODE REVIEW

**Comment by tchoutri** [comment]
@jkarni would you mind giving your opinion on this?

**Comment by tchoutri** [comment]
@DavidMazarro Thanks for the PR!

**Review by jkarni — APPROVED** [review]
Looks good to me!

**Comment by DavidMazarro** [comment]
(I added these last two commits because I was unfamiliar with `doctest` and didn't know the code examples were checked, my bad!)

**Comment by DavidMazarro** [comment]
Feel free to run the CI on this one again, but other than that it's ready to merge from my side :)

**Comment by DavidMazarro** [comment]
@tchoutri could you run the CI workflow again?

**Comment by tchoutri** [comment]
Alright, I have looked up the usage of `AtLeastOneFragment` across openn-source codebases on github and hackage, looks like we can get away with this breaking change.

Thanks @DavidMazarro!

**Pull request merged**
