### PR TITLE
renaming: Config -> Context

### PR DESCRIPTION
**Pull request by soenkehahn**
In relation to #361. Please, review.

### CODE REVIEW

**Comment by codedmart** [comment]
I like this change. LGTM :+1:

**Comment by arianvp** [comment]
Do we still want to change `HasNamedContext` => `InNamedContext` ?

**Comment by fizruk** [comment]
@arianvp where is `HasNamedContext` defined? I can't see one.

**Comment by soenkehahn** [comment]
@arianvp: Maybe we should discuss your suggestion in #361? And merge this? (I.e. can I get another `LGTM`, please? :) )

**Comment by fizruk** [comment]
@soenkehahn you have my LGTM :)

**Pull request merged**
