### PR TITLE
Add note to custom monad documentation about what to do with Raw endpoints

### PR DESCRIPTION
**Pull request by xaviershay**
Took me a decent amount of googling to figure this out. I believe this is the currently recommended way? As a relatively new user, I was surprised this was not available in the core package.

cc @cdepillabout

Ref #785 and #819.

### CODE REVIEW

**Comment by cdepillabout** [comment]
> As a relatively new user, I was surprised this was not available in the core package.

As was I.

If any of the Servant devs want to pull the code from my `servant-rawm` package into `servant` proper (and then deprecating `servant-rawm`, I'd be interested in helping.

As far as I can tell, the `RawM` type from `servant-rawm` is strictly superior to `Raw`.

**Comment by phadej** [comment]
What's the motivation to using `RawM`. What you have in your custom monads to pass to *raw* `Application`? Is there something missing in `servant` that you *have to* rely on `Raw`? Could you write a cookbook recipe explaining that?

`Raw` is a bit like `unsafePerformIO`, an escape hatch; I want to know where servant isn't good enough.

**Comment by xaviershay** [comment]
> What's the motivation to using RawM. What you have in your custom monads to pass to raw Application?

I want to generate server-side events. My custom monad contains accessors to relevant state:

https://github.com/xaviershay/licross/commit/ac45272ba0e57c0ea5978470af3207bfd6cb3ae1
https://github.com/xaviershay/licross/commit/9b70441c616a5637de56f7d0890f32e41d73b0f3

(Obviously this isn't finished yet!)

**Comment by cdepillabout** [comment]
@alpmestan That's basically what `RawM` does:

https://github.com/cdepillabout/servant-rawm/blob/b4c7d4b2d183a5f83199b0ea85eaffd5e6ad6c83/src/Servant/RawM/Internal/Server.hs#L51

(It also adds a phantom parameter you can use to attach `servant-docs` to.)

From my use of `servant-rawm`, this seems to work well.

Originally I posted about this in https://github.com/haskell-servant/servant/issues/819, but there didn't seem to be any interest, so I just kept it as a separate package.  I'd be happy to deprecate that package if the definition of `ServerT m Raw` changed to `m Application`.  Although it would be nice to have an additional phantom parameter to attach documentation to, in case you use multiple `Raw` in your API.

**Comment by alpmestan** [comment]
Well, in an ideal world, we have less and less `Raw`s, turning many into new, dedicated combinators for well-specified tasks, like file serving.

**Comment by cdepillabout** [comment]
> `RawM` is definitely useful and we should advertise it, so I'm fine merging this documentation patch.

In addition to this, if any of the current (or future?) servant maintainers want push access to the `servant-rawm` respository (and Hackage package), I'd be happy to do that.

**Pull request merged**
