### PR TITLE
Tutorial

### PR DESCRIPTION
**Pull request by soenkehahn**
These are the two tutorial branches merged. There's still lots of work to do.

I wrote a small script to convert from birdtrack syntax to backtrack-markdown-syntax, since sphinx doesn't understand `.lhs`: `servant-examples/tutorial/convert.hs`. I haven't committed any of the changes it produces, since I thought that would be more confusing than helpful at this point.

One problem is that the sphinx syntax highlighting for haskell seems to choke on fancier features like `TypeOperators`. :( I'm currently out of ideas, what to do about that.

@jkarni @fizruk

### CODE REVIEW

**Comment by soenkehahn** [comment]
Fixes #338.

**Comment by soenkehahn** [comment]
@jkarni: you added a top-level stack file. Is the plan to migrate travis to `stack` then? If not, I think the the stack file should be inside `doc/tutorial`.

**Comment by soenkehahn** [comment]
Fixes #360.

**Comment by soenkehahn** [comment]
I'd appreciate reviews. Apart from that, this is ready to be merged. @haskell-servant/maintainers

**Comment by jkarni** [comment]
> @jkarni: you added a top-level stack file. Is the plan to migrate travis to stack then? If not, I think the stack file should be inside doc/tutorial.

@soenkehahn Not sure what you mean. It wasn't my intention to migrate to stack. However. I am in favour of not having a separate stack file for this, since:
   - This is what we've been doing with all other packages
   - This way it's easier to check locally (for those using stack) that the tutorial also compiles fine (I'd `stack test` to basically be all I have to run to know everything is fine, and CI should pass, so that it's intuitive for people what they have to do to know that everything worked)

**Comment by jkarni** [comment]
I'm going to rebase against master, and also squash some of my commits. Force pushes coming up in the next ~1h.

**Comment by jkarni** [comment]
LGTM (after CI)

**Pull request merged**
