### PR TITLE
WIP: Fix issue #285

### PR DESCRIPTION
**Pull request by arianvp**
This should fix issue #285 . 

I'm wondering if we could write some sort of regression test suit using `nodejs` or http://phantomjs.org/ to catch these kind of bugs.

### CODE REVIEW

**Comment by alpmestan** [comment]
We definitely could should have more tests for this yes =)

Also, if some API doesn't support JSON then the devs wouldn't be able to use `servant-js`. If anyone wants to try and make more content types work, that would be very appreciated!

**Comment by jkarni** [comment]
Should we merge this for now and add tests as a separate story?

**Comment by arianvp** [comment]
Yes seems good.

**Comment by jkarni** [comment]
Thanks!

**Pull request merged**
