### PR TITLE
Changed so two titles are displayed correctly

### PR DESCRIPTION
**Pull request by rwobben**
Solves #367

### CODE REVIEW

**Comment by alpmestan** [comment]
LGTM. @soenkehahn can you check this is OK?

**Comment by soenkehahn** [comment]
Can't be worse than before. :)

**Comment by soenkehahn** [comment]
Merged.

**Comment by soenkehahn** [comment]
@rwobben: Thanks for the patch.

Why did you say this was about two titles? I only saw one title changed.

**Comment by rwobben** [comment]
Yes, I thought I was 2 tityles but it was one title two times.
First  I made it a good looking title and later on I deleted the word title in the title so it looks more as the other one.

**Pull request closed without merging**
