### PR TITLE
Minor bug fix for HasLink

### PR DESCRIPTION
**Pull request by vwwv**
As discuss on the issue https://github.com/haskell-servant/servant/issues/527 .

### CODE REVIEW

**Comment by phadej** [comment]
As you can see this is a *breaking change*. Would force us to bump versions to `0.9` (and need to fix test suites as well).

**Comment by vwwv** [comment]
Thanks for your quick feedback! yes, it is a breaking change (btw, my bad I did not see it had to modify the test suites).

Could it be an option to patch to this PR a modification to the test suite so the change could be added later on a version update? (I mean, this tiny change is probably not worth a version change, but maybe could be added in a future when there's a version change anyway).

**Comment by soenkehahn** [comment]
> I mean, this tiny change is probably not worth a version change [...]

@vwwv: Don't worry about this being a breaking change. We'd much rather release more often with major version bumps than letting people wait for features to land on hackage.

It'd be nice if you:

- mention in one of the commit messages that this is a breaking change,
- add something to the `CHANGELOG` and
- of course, fix the travis build.

**Comment by vwwv** [comment]
@soenkehahn: thanks for the advise, I'll add those suggestions to the PR in a couple days.

**Comment by phadej** [comment]
Merged in #666. Thanks again for spotting this issue.

**Pull request closed without merging**
