### PR TITLE
Add hoistServer to HasServer

### PR DESCRIPTION
**Pull request by phadej**
This is a refinement of an idea by @paf31.

I'll do documentation pass and add tests, if the idea is OK.

### CODE REVIEW

**Comment by phadej** [comment]
I'd only deprecate `enter`, and keep it around for few major releases

**Comment by phadej** [comment]
@alpmestan, should I rewrite whole `Enter` section in the tutorial (i.e. only mention it existed?)

**Comment by alpmestan** [comment]
@phadej Well, we definitely want to explain the new stuffs. And maybe indeed add a little sentence or two that says "it replaces `Enter`, just do this to port your `enter`-based code over to `hoistServer`" ?

**Comment by phadej** [comment]
@alpmestan I'll merge this now and update tutorial in separate PR (as I  guess there will be much more to review).

**Comment by alpmestan** [comment]
@phadej very good idea :)

**Pull request merged**
