### PR TITLE
Fix markdown indentation and compilation warning

### PR DESCRIPTION
**Pull request by rsoeldner**
The code indention of the Response does not get correctly rendered on github.

### CODE REVIEW

**Comment by rsoeldner** [comment]
I dont know why travis failes, test seems to pass ....

**Comment by phadej** [comment]
Error is due `servant-auth-server`, ping @domenkozar, could you fix the `master`. I'll make Hackage revisions soon-ish.
```
[;1msrc/Servant/Auth/Server/SetCookieOrphan.hs:10:10: [;1m[31merror:[0m[0m[;1m[0m[0m[;1m
    Duplicate instance declarations:
      instance FromHttpApiData SetCookie
        -- Defined at src/Servant/Auth/Server/SetCookieOrphan.hs:10:10
      instance FromHttpApiData SetCookie
        -- Defined in â€˜Web.Internal.HttpApiDataâ€™[0m[0m
```

**Comment by phadej** [comment]
restarted build

**Comment by rsoeldner** [comment]
@phadej do you have any thoughts / suggested on this?

**Comment by anisjonischkeit** [comment]
Is there anything I can do to help get this over the line?

**Pull request merged**
