### PR TITLE
Add Basic Authentication to tutorial

### PR DESCRIPTION
**Pull request by aaronlevin**

### CODE REVIEW

**Comment by soenkehahn** [comment]
@aaronlevin: Thanks!

Are you looking into the travis failures?

Also, could you introduce line wrapping, please? (Not saying I prefer line wrapped files, but I think it should be consistent across the tutorial.)

**Comment by soenkehahn** [comment]
Also, I would prefer not putting documentation about authentication in the different sections, but adding a new section that is specifically dedicated to auth. @aaronlevin: Do you agree? Would you be up for changing your PR?

(This shouldn't block merging IMO, though.)

**Comment by aaronlevin** [comment]
Sure. I can add a section on authentication and try to figure out the
Travis failures!

**Comment by soenkehahn** [comment]
Thanks a lot.

**Comment by aaronlevin** [comment]
@soenkehahn ok, i made the changes, but before I can build this I need to merge in the changes to master. I tried to do a rebase against master and hit some walls right away.

**Comment by jkarni** [comment]
This is failing. From CI:

```
ApiType.lhs:338:1:

    Multiple declarations of ‘User’

    Declared at: ApiType.lhs:35:1

                 ApiType.lhs:338:1

ApiType.lhs:339:3:

    Multiple declarations of ‘User’

    Declared at: ApiType.lhs:35:13

                 ApiType.lhs:339:3
```

**Comment by jkarni** [comment]
Closing in favour of #416

**Pull request closed without merging**
