### PR TITLE
Add Functor instance to AuthHandler.

### PR DESCRIPTION
**Pull request by torgeirsh**

### CODE REVIEW

**Review by tchoutri — CHANGES_REQUESTED** [review]
Hi, and thank you for this PR! Could you please add a changelog entry? :)

**Comment by torgeirsh** [comment]
Certainly! Is this the correct format?

**Review by tchoutri — APPROVED** [review]

**Comment by tchoutri** [comment]
> Certainly! Is this the correct format?

@torgeirsh all good :)

**Comment by ysangkok** [comment]
This is now released on Hackage as part of [servant-0.20](https://hackage.haskell.org/package/servant-0.20).

**Pull request merged**
