### PR TITLE
release 0.8

### PR DESCRIPTION
**Pull request by soenkehahn**
Can someone please review whether a minor version bump is allowed? And whether it's what we want?

Thanks!

@haskell-servant/maintainers

### CODE REVIEW

**Comment by jkarni** [comment]
Maybe rename the PR to release 0.8? 

Otherwise, LGTM. I imagine the `NoContent` changes caused a merge conflict.

**Comment by soenkehahn** [comment]
> Maybe rename the PR to release 0.8?

Done.

> I imagine the `NoContent` changes caused a merge conflict.

I've just rebased on `master` and had to fix one conflict in `servant-js.cabal`. Is that what you mean?

**Comment by phadej** [comment]
Why this is `0.8`, what are the breaking changes? None of

> Minor fixes, documentation changes and cabal tweaks

is breaking change?

---

Related to this, labelling pull requests with *breaking change* label could help tracking whether breaking changes were merged.

**Comment by jkarni** [comment]
:+1: on labeling. Some of the `NoContent` changes were not backwards compatible. @soenkehahn may have had other changes in mind, though.

**Comment by soenkehahn** [comment]
No, it was necessary for the `NoContent` stuff. (cc: @arianvp)

**Pull request merged**
