### PR TITLE
Make ServantErr throwable

### PR DESCRIPTION
**Pull request by eskimor**
Being able to throw an error is useful at times.

### CODE REVIEW

**Comment by eskimor** [comment]
e.g. to implement something like yesod-persistent's get404. It needs to be an exception to roll back the database transaction, just catching them at the toplevel and delivering them to the user seems reasonable.

**Comment by fizruk** [comment]
Looks good to me! :+1:

@haskell-servant/maintainers any objections?

**Comment by alpmestan** [comment]
LGTM.

**Comment by soenkehahn** [comment]
I would remove the comment. In any case LGTM.

**Pull request merged**
