### PR TITLE
Bugfix release

### PR DESCRIPTION
**Pull request by christian-marie**
WIP, review only, no merge yet.

I'm thinking of naming this: 0.4.3

I think it's a nice name.

If we are all OK with the name and the commits included I'll bump and add some words to the changelog, and make the tests all happy, etc.

### CODE REVIEW

**Comment by christian-marie** [comment]
OK I think this is a release!

Any more patches? If not, feel free to merge this, I'll tag it and upload.

**Comment by christian-marie** [comment]
I could have sworn someone asked me to fix something and add that to the bugfix release, but I can't find the issue anywhere.

**Comment by christian-marie** [comment]
It was #122, does anyone want to get a patch together to resolve that? Otherwise this bugfix release is good to go.

**Comment by alpmestan** [comment]
Once #122 is fixed, it seems we are indeed good to go :+1:

Thanks for all the time you've put into this!

**Comment by christian-marie** [comment]
Will merge when CI is OK.

**Pull request merged**
