### PR TITLE
allow filepath versions < 1.6

### PR DESCRIPTION
**Pull request by BebeSparkelSparkel**
Able to compile with updated `lens` https://github.com/ekmett/lens/pull/1054

### CODE REVIEW

**Comment by tchoutri** [comment]
We probably need to drop GHC <8.10

**Comment by Kleidukos** [comment]
@BebeSparkelSparkel would you mind rebasing on current HEAD?

**Comment by tchoutri** [comment]
@BebeSparkelSparkel would you mind rebasing on current HEAD?

**Comment by ysangkok** [comment]
Since 

* https://github.com/haskell-unordered-containers/hashable/pull/290

won't get merged any time soon, there is no rush with this.

**Comment by ysangkok** [comment]
@BebeSparkelSparkel  if you want progress on this, I think it would make most sense to figure out the doctest failure on #1765. Because filepath is a boot library, so it's better to just upgrade it with everything else.

**Comment by ysangkok** [comment]
closing this since #1765 got merged

**Pull request closed without merging**
