### PR TITLE
Redo Enter

### PR DESCRIPTION
**Pull request by phadej**
"Fixes" #734

### CODE REVIEW

**Comment by fizruk** [comment]
Nice!

Can we also add some custom `TypeError`s here?
Otherwise I except there to be some unreadable type errors.

Can we interpret `Enter` as a closed function (type-level to term-level) and disallow any other instances (filling the holes with custom type errors)?

**Comment by phadej** [comment]
I guess we can drop the `ret` from `Enter` definition; and have a `TypeError` in `Entered`.
Via constraints the GHC should be able to reason "back" `ret -> typ` anyway.

**Comment by alpmestan** [comment]
I still think `Nat` is the wrong thing to use there. Enter should really just be about walking down `:<|>`-separated stuffs, idealy. But +1 as this improves on the status quo.

**Comment by fizruk** [comment]
@alpmestan where's the prior discussion about `:~>` and why we generalised over it?
Can you link it here?

**Comment by phadej** [comment]
I guess it may work with generic `transform`, not `m :~> n`, but then we have to specify that it can be inverted (that what `enter`'s functional dependencies force us to do). Not sure how the lack of injectivity (if we don't' want to specify the inverse) would work.

**Comment by alpmestan** [comment]
> @alpmestan where's the prior discussion about :~> and why we generalised over it?
Can you link it here?

@fizruk I'm not sure there ever was a discussion about generalizing the kind of transformation we can apply, as the original motivation for `Enter` was to go from a monad to another. It's just been on my personal wishlist for years. I think `Enter` should allow us to apply any transformation "that can be applied on the given chain of `:<|>`-separated stuffs", whatever those `:<|>`-separated stuffs are. I ideally would like a solution such that "if the types align, we should be able to do it". But I don't want to block this PR on that, just using the occasion to maybe pull you guys down that rabbit hole with me =)

**Comment by phadej** [comment]
@alpmestan in this case we have to fuse old `Enter` with `m :~> n` so we can more specifically write
"if you have `typ` api, you'll get `ret` api". We could use defunctionalization to make `Enter` generic, but that is far from elegant (IMHO).

**Comment by phadej** [comment]
@fizruk how urgent this is for you; I'd like to release 0.11 only after ZuriHac + few weeks; as then there
might be other major stuff in (e.g. `Lenient` params)

**Comment by fizruk** [comment]
@phadej not urgent, I have a workaround in place for now.

**Pull request merged**
