### PR TITLE
allow filepath versions < 1.6, rebased

### PR DESCRIPTION
**Pull request by ysangkok**
Rebased version of #1724

### CODE REVIEW

**Comment by ysangkok** [comment]
Rebased as requested @tchoutri

**Comment by ysangkok** [comment]
Doesn't seem to actually work right now:

```
 % cabal build -c 'filepath >= 1.5' all
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: cookbook-basic-auth-0.1 (user goal)
[__1] trying: base-4.19.1.0/installed-eafb (dependency of cookbook-basic-auth)
[__2] trying: cookbook-openapi3-2.2 (user goal)
[__3] trying: servant-swagger-ui-0.3.5.5.0.0 (dependency of cookbook-openapi3)
[__4] trying: file-embed-lzma-0.0.1 (dependency of servant-swagger-ui)
[__5] next goal: filepath (dependency of file-embed-lzma)
[__5] rejecting: filepath-1.5.2.0 (conflict: file-embed-lzma =>
filepath>=1.1.4.1 && <1.5)
```

**Comment by tchoutri** [comment]
Ok we can wait for GHC 9.10 to be released. :)

**Comment by tchoutri** [comment]
@ysangkok I believe the time has come.

**Comment by ysangkok** [comment]
But file-embed-lzma hasn't been revised to allow GHC 9.10. So we're still blocked on the same issue.

**Pull request closed without merging**
