### PR TITLE
Oleg testcase 1091

### LINKED ISSUE #1091: client streaming + http redirect result into runtime exception
If an http endpoint returns a redirect (for example http -> https upgrade), streaming client errors out:

```
HasClient @StreamBody
CallStack (from HasCallStack):
  error, called at src/Servant/Client/Core/Internal/HasClient.hs:550:44 in servant-client-core-0.15-KKVc3oxuLh47HhicA3CWtB:Servant.Client.Core.Internal.HasClient                                                                                                                                                     
```

https://github.com/haskell-servant/servant/blob/master/servant-client-core/src/Servant/Client/Core/Internal/HasClient.hs#L550

### PR DESCRIPTION
**Pull request by phadej**
@domenkozar can you check this works for your use-case?

Fixes #1091

### CODE REVIEW

**Comment by domenkozar** [comment]
Something is not right, my backend is returning 502 (although there's nothing in server logs). I'll look into it.

**Comment by phadej** [comment]
@domenkozar thanks, let's make this right this time :)

**Comment by domenkozar** [comment]
Figured out the problem, I was using `OctetStream` while I have my own mimetype. I think there's a bug in servant though, it should return 400 or something similar instead of 503.

Nevertheless, this now works. Could we get a bugfix release for 0.15?

**Comment by phadej** [comment]
@domenkozar let's see. Looks more like that we'll have `servant-client(-core)-0.16`

**Pull request merged**
