### PR TITLE
Re-export `throwError` from module `Servant`

### LINKED ISSUE #442: Re-export `throwE` from module `Servant`

### PR DESCRIPTION
**Pull request by lcycon**
Fixes #442

### CODE REVIEW

**Comment by arianvp** [comment]
Looks good. LGTM

**Comment by soenkehahn** [comment]
LGTM.

I think we should also then use `throwError` in the tutorial (and maybe even in the test-suite). To make it more discoverable. Currently there are some uses of `throwE` in there.

@lcycon: Would you want to take care of this in this PR or should I merge as is?

**Comment by lcycon** [comment]
I'll amend this pull request sometime tomorrow to include some doc changes
and whatnot

L

**Comment by soenkehahn** [comment]
@lcycon: Oh, and if you think it's reasonable add something to the changelog, please.

**Comment by lcycon** [comment]
@soenkehahn Weren't very many references in the docs, but I changed those that were.

**Comment by lcycon** [comment]
I... uh... don't know how that happened?

**Comment by 3noch** [comment]
You can reopen it no?

**Comment by lcycon** [comment]
Nope. "No new commits"

**Comment by lcycon** [comment]
Oh I know what happened. Standby

**Comment by kosmikus** [comment]
@lcycon Did you accidentally update the branch that is the source of this PR? There really don't seem to be any commits in this PR right now ...

**Comment by lcycon** [comment]
Alright. Think I fixed it

**Comment by lcycon** [comment]
Life lessons: Never write git aliases when you haven't had your morning tea yet heh

**Comment by soenkehahn** [comment]
@lcycon: I would've expected the changes to the changelog to only be in `servant-server`, since that is where the change happened. Why did you also change the changelogs of `servant` and `servant-docs` (and not, say, `servant-client`)? In the past the changelogs only listed changes to that particular package.

In general we're not really all that happy with the changelog procedure. @kosmikus had the idea of merging all the changelogs of the `servant` repo into one. Which I think I like. (Unrelated to this PR, of course.)

**Comment by lcycon** [comment]
@soenkehahn I found a few cases where it looked like (from the Git history) that a single component change added changelogs to docs, the root `Servant` package, and anyone else it touched. Long story short: multiple changelogs was confusing, I tried to (apparently poorly) emulate what it looked like you were all doing

**Comment by lcycon** [comment]
@soenkehahn I've updated it. I left the entry to the `servant-docs` changelog, but amended it to reflect the actual changes made. Let me know if I'm still off the mark from what y'all are aiming for changelog-wise

**Comment by soenkehahn** [comment]
@lcycon: Well, turns out we don't really know what we're doing regarding changelogs. :)

But everything looks good now. I'll merge.

**Comment by soenkehahn** [comment]
@lcycon: Merged. Many thanks!

**Pull request merged**
