### PR TITLE
Make servant compilable with GHC8

### PR DESCRIPTION
**Pull request by phadej**
Part of https://github.com/haskell-servant/servant/issues/384

GHC8.0 is more conservative when deducing context

### CODE REVIEW

**Comment by phadej** [comment]
Made a bit more changes. `stack-ghc-8.0.1.yaml` is a bit of a lie. `stack build` works on my Ubuntu, except `servant-js` fails to link. I don't know why. Tests cannot be run, as e.g. `doctest` isn't ghc8.0 ready yet.

**Comment by jkarni** [comment]
Thanks - I'm going to look into CI for 8.0 before merging.

**Comment by jkarni** [comment]
@phadej can you rebase? I think it actually makes sense to merge this before setting up 8.0 CI.

**Comment by hvr** [comment]
Just fyi, the recently released servant-0.5 with a recent GHC 8.0RC:

```
Resolving dependencies...
Failed to install servant-0.5
Build log ( /tmp/extra25612243857/.cabal-sandbox/logs/servant-0.5.log ):
Configuring servant-0.5...
Dependency aeson ==0.11.1.1: using aeson-0.11.1.1
Dependency attoparsec ==0.13.0.1: using attoparsec-0.13.0.1
Dependency base ==4.9.0.0: using base-4.9.0.0
Dependency base-compat ==0.9.0: using base-compat-0.9.0
Dependency bytestring ==0.10.7.0: using bytestring-0.10.7.0
Dependency bytestring-conversion ==0.3.1: using bytestring-conversion-0.3.1
Dependency case-insensitive ==1.2.0.6: using case-insensitive-1.2.0.6
Dependency http-api-data ==0.2.2: using http-api-data-0.2.2
Dependency http-media ==0.6.3: using http-media-0.6.3
Dependency http-types ==0.9: using http-types-0.9
Dependency network-uri ==2.6.1.0: using network-uri-2.6.1.0
Dependency string-conversions ==0.4: using string-conversions-0.4
Dependency text ==1.2.2.1: using text-1.2.2.1
Dependency vault ==0.3.0.6: using vault-0.3.0.6
Using Cabal-1.24.0.0 compiled by ghc-8.0
Using compiler: ghc-8.0.0.20160316
Using install prefix: /tmp/extra25612243857/.cabal-sandbox
Binaries installed in: /tmp/extra25612243857/.cabal-sandbox/bin
Libraries installed in:
/tmp/extra25612243857/.cabal-sandbox/lib/x86_64-linux-ghc-8.0.0.20160316/servant-0.5-KSlWpDmEDyKLglz0ZGAKvg
Private binaries installed in: /tmp/extra25612243857/.cabal-sandbox/libexec
Data files installed in:
/tmp/extra25612243857/.cabal-sandbox/share/x86_64-linux-ghc-8.0.0.20160316/servant-0.5
Documentation installed in:
/tmp/extra25612243857/.cabal-sandbox/share/doc/x86_64-linux-ghc-8.0.0.20160316/servant-0.5
Configuration files installed in: /tmp/extra25612243857/.cabal-sandbox/etc
Using alex version 3.1.4 found on system at: /opt/alex/3.1.4/bin/alex
Using ar found on system at: /usr/bin/ar
Using c2hs version 0.26.1 found on system at: /home/hvr/.cabal/bin/c2hs
Using cpphs version 1.19.2 found on system at: /home/hvr/.cabal/bin/cpphs
Using gcc version 4.9.2 found on system at: /usr/bin/gcc
Using ghc version 8.0.0.20160316 given by user at: /opt/ghc/8.0.1/bin/ghc
Using ghc-pkg version 8.0.0.20160316 found on system at:
/opt/ghc/8.0.1/bin/ghc-pkg
No ghcjs found
No ghcjs-pkg found
No greencard found
Using haddock version 2.17.0 found on system at: /opt/ghc/8.0.1/bin/haddock
Using happy version 1.19.5 found on system at: /opt/happy/1.19.5/bin/happy
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.67 found on system at: /opt/ghc/8.0.1/bin/hpc
Using hsc2hs version 0.67 found on system at: /opt/ghc/8.0.1/bin/hsc2hs
No hscolour found
No jhc found
Using ld found on system at: /usr/bin/ld
No lhc found
No lhc-pkg found
Using pkg-config version 0.28 found on system at: /usr/bin/pkg-config
Using strip version 2.25 found on system at: /usr/bin/strip
Using tar found on system at: /bin/tar
No uhc found
Component build order: library
creating dist/dist-sandbox-b774497d/build
creating dist/dist-sandbox-b774497d/build/autogen
Building servant-0.5...
/opt/ghc/8.0.1/bin/ghc-pkg init dist/dist-sandbox-b774497d/package.conf.inplace
Preprocessing library servant-0.5...
Building library...
creating dist/dist-sandbox-b774497d/build
/opt/ghc/8.0.1/bin/ghc --make -fbuilding-cabal-package -O -static -dynamic-too -dynosuf dyn_o -dynhisuf dyn_hi -outputdir dist/dist-sandbox-b774497d/build -odir dist/dist-sandbox-b774497d/build -hidir dist/dist-sandbox-b774497d/build -stubdir dist/dist-sandbox-b774497d/build -i -idist/dist-sandbox-b774497d/build -isrc -idist/dist-sandbox-b774497d/build/autogen -Idist/dist-sandbox-b774497d/build/autogen -Idist/dist-sandbox-b774497d/build -Iinclude -optP-include -optPdist/dist-sandbox-b774497d/build/autogen/cabal_macros.h -this-unit-id servant-0.5-KSlWpDmEDyKLglz0ZGAKvg -hide-all-packages -no-user-package-db -package-db /tmp/extra25612243857/.cabal-sandbox/x86_64-linux-ghc-8.0.0.20160316-packages.conf.d -package-db dist/dist-sandbox-b774497d/package.conf.inplace -package-id aeson-0.11.1.1-GIIGOlfo51N2EBirJ6q3br -package-id attoparsec-0.13.0.1-BGKnQ44Ozt81WRNLmD6bIA -package-id base-4.9.0.0 -package-id base-compat-0.9.0-L9pYmcL2GkfGM4pygxpdD0 -package-id bytestring-0.10.7.0 -package-id bytestring-conversion-0.3.1-JiePqFZ5wkEFJp5gDhPMXN -package-id case-insensitive-1.2.0.6-LaPBTobF0F4OjyupPG8nO -package-id http-api-data-0.2.2-8Vnfvu0j1LIEqLkZCQDmZT -package-id http-media-0.6.3-1Py8iwxJK9l2aKzqmXMPbB -package-id http-types-0.9-KF2nPttT6OnEAOc9rQzkGR -package-id network-uri-2.6.1.0-1CNfNSH4L866VyR8SXucpF -package-id string-conversions-0.4-Dtd2ldygOZI8fKU32EOSg7 -package-id text-1.2.2.1-7JRQ5fRT7lI5k1iMwAs2jA -package-id vault-0.3.0.6-7i0wAB5uOFbDhUHXkNIvph -XHaskell2010 Servant.API Servant.API.Alternative Servant.API.BasicAuth Servant.API.Capture Servant.API.ContentTypes Servant.API.Experimental.Auth Servant.API.Header Servant.API.HttpVersion Servant.API.Internal.Test.ComprehensiveAPI Servant.API.IsSecure Servant.API.QueryParam Servant.API.Raw Servant.API.RemoteHost Servant.API.ReqBody Servant.API.ResponseHeaders Servant.API.Sub Servant.API.Vault Servant.API.Verbs Servant.API.WithNamedContext Servant.Utils.Links -Wall
[ 1 of 20] Compiling Servant.API.Experimental.Auth ( src/Servant/API/Experimental/Auth.hs, dist/dist-sandbox-b774497d/build/Servant/API/Experimental/Auth.o )
[ 2 of 20] Compiling Servant.API.Raw  ( src/Servant/API/Raw.hs, dist/dist-sandbox-b774497d/build/Servant/API/Raw.o )
[ 3 of 20] Compiling Servant.API.ContentTypes ( src/Servant/API/ContentTypes.hs, dist/dist-sandbox-b774497d/build/Servant/API/ContentTypes.o )

src/Servant/API/ContentTypes.hs:172:10: error:
    • Could not deduce (AllMime cts)
        arising from the superclasses of an instance declaration
      from the context: AllMimeRender (ct : cts) a
        bound by the instance declaration
        at src/Servant/API/ContentTypes.hs:172:10-67
      Possible fix:
        add (AllMime cts) to the context of the instance declaration
    • In the instance declaration for ‘AllCTRender (ct : cts) a’
xcabal: Error: some packages failed to install:
servant-0.5 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by soenkehahn** [comment]
Before we have CI for `ghc-8` I expect this to be somewhat brittle. I guess most people still use `ghc-7` and we can't really blame anyone for merging something to master that breaks compatibility with `ghc-8` without CI.

I'm not strictly against merging this, but without CI we shouldn't pretend that `servant` reliably supports `ghc-8`.

**Comment by soenkehahn** [comment]
I would also be fine with lowering the upper bounds for `base` in the cabal file to disallow `ghc-8`.

**Comment by phadej** [comment]
I'll rebase

**Comment by hvr** [comment]
> I'm not strictly against merging this, but without CI we shouldn't pretend that servant reliably supports ghc-8.

That's perfectly fine, but by having inaccurate/missing upper bounds, and specifically advertising  `base < 5`  you effectively are claiming that server-0.5 is compatible with base-4.9 and GHC 8.0... :-/

**Comment by phadej** [comment]
Travis setup is trickier, as we cannot yet run all tests (especially doctests)

**Comment by soenkehahn** [comment]
@hvr: Yeah, `base < 5` is a bit unfortunate. Personally I would have gone with no bounds for base at all, but hackage complains about that.

Personally I don't really care about this so much. @phadej: Would you be fine with setting `base < 4.9` on `master`?

@phadej: Are you planning to work on this? If yes, what's your plan? It would be great to have a stack file that actually allows to install the needed `ghc`. Also, I was thinking it would be good to move this line [https://github.com/haskell-servant/servant/blob/master/.travis.yml#L28] into a bash script and call that from the travis file. All this would make it easier to run the tests at least locally.

**Comment by hvr** [comment]
@soenkehahn no bounds at all are in violation with Hackage's guidelines, as they violate the PVP and cause Hackage Trustees additional workload that would be easily avoidable, and in the long-term cause more cabal-edits resulting in additional index-bloat... long story short, the Cabal/Hackage infrastructure is optimised for the PVP and inaccurate version bounds cause penalties.

**Comment by soenkehahn** [comment]
@hvr: I didn't want to get into a debate about upper bounds. :) I just wanted to give some insight into why we ended up with `base < 5`. Which in any case doesn't really make much sense as an upper bound.

**Comment by phadej** [comment]
And I made a revision on `servant-0.5` (which hopefully restricts other `servant-*` packages) https://hackage.haskell.org/package/servant-0.5 as Cabal found an install plan for it with GHC-8.0, which failed.

If it's ok to setup travis job using `stack` (we can still use tinc for cabal-like builds), I'll do it right away, if that helps merging this PR.

**Comment by soenkehahn** [comment]
@phadej: Sorry, maybe you missed this: Are you fine with changing to `base < 4.9` on `master`?

Regarding `stack` for CI: I'm a bit worried about the additional complexity to the ci script, if we use two different tools for different compiler versions. Why do you want to do it with `stack` though? It looks like `ghc-8` could be easily added to the current CI script: https://travis-ci.org/haskell-servant/servant/jobs/118668359.

**Comment by phadej** [comment]
Yes `base <4.9` is ok, if we don't want to bother with GHC8.0 support till now.

I proposed stack, as I don't know how to skip tests with `tinc`. E.g. the job you linked isn't helpful at all, as it fails to install dependencies. Skipping tests would be lesser bad, as it will catch GHC8.0 build issues.

**Comment by soenkehahn** [comment]
@phadej: I thought that the most difficult part of getting CI to work was to install the compiler. That's why I tried this out. (Getting `doctest` to work also seems feasable. There's a branch that seems to work with `ghc-8` and `tinc` allows to specify dependencies from github by commit hash.)

I'll lower the bound for `base` then.

**Comment by sol** [comment]
@soenkehahn @phadej fyi: https://twitter.com/solirc_/status/715220736902717440

**Comment by phadej** [comment]
@sol see https://github.com/haskell-servant/servant/pull/473, this PR is obsolete.

**Pull request closed without merging**
