### PR TITLE
Document the type of endpoint a parameter belongs to

### LINKED ISSUE #760: servant-docs and QueryParam
If I have a `QueryParam` in a path ending with a `Post`, and generate documentation for it with servant-docs, then it prints out that it is a `GET Parameter`... which looks out of place.

### PR DESCRIPTION
**Pull request by ivan-m**
Closes #760

### CODE REVIEW

**Comment by ivan-m** [comment]
I'm not sure if this is the right approach or if they should just be referred to as query parameters.

**Comment by phadej** [comment]
conflict

**Comment by ivan-m** [comment]
Conflict resolved.

**Comment by phadej** [comment]
@ivan-m, if you could write CHANGELOG.md entries for your recent changes to `servant-docs` it would be super great.  just make `next` section. (or if there are breaking changes, then bump directly to `0.12`)

**Pull request merged**
