### PR TITLE
Make tutorial/example code compile.

### PR DESCRIPTION
**Pull request by diekmann**
Document where to find the dependencies to make the tutorial compile.

### CODE REVIEW

**Comment by jkarni** [comment]
LGTM

**Comment by jkarni** [comment]
Well - slight problem. Now *every* version of the tutorial will point to `master` of the cabal file. Ideally, version 0.8 (from git tag 0.8) would point to the cabal file for that tag, and so on.

**Comment by diekmann** [comment]
Right, ...
I just couldn't find where the github links are defined.
By the way, the "Edit on GitHub" link (top right of the tutorial page) also points to a 404 github page.

**Comment by jkarni** [comment]
@diekmann thanks for the heads up about edit on github. Looks like it's because of [this](https://github.com/rtfd/readthedocs.org/issues/2130).

**Comment by jkarni** [comment]
There's an [issue](https://github.com/rtfd/readthedocs.org/issues/2195) with old branches, so the 'stable' doc points to something that no longer exists (ugh), but for everything else `Edit on Github` should be working.

**Comment by diekmann** [comment]
Updated link to cabal file. Cannot fix "Edit on GitHub"-issue.

**Comment by soenkehahn** [comment]
I think pointing to the `v0.8` branch is a bad idea, since we would have to update that manually every time we cut a new release. (It's already outdated, since we have `v0.8.1` now.) On the other hand I think pointing to the version of `master` is not *that* bad.

**Comment by jkarni** [comment]
RTD allows us to link to the correct version: http://read-the-docs.readthedocs.io/en/latest/vcs.html

**Comment by diekmann** [comment]
Maybe someone with RTD access should finish this pull request ;-)

**Comment by alpmestan** [comment]
The tutorial & cookbook are now CI checked, can we close this?

**Comment by diekmann** [comment]
Sure, thanks!

**Comment by alpmestan** [comment]
Thank you, and sorry for dropping the ball on this one, but at least it happened :-)

**Pull request closed without merging**
