### PR TITLE
Tweak the HasLink instance for QueryParam, fixes #129

### LINKED ISSUE #129: Link for 'QueryParam sym v' asks for a value of type 'v' instead of 'Maybe v'
From `Servant.Utils.Link`:

``` haskell
instance (KnownSymbol sym, ToText v, HasLink sub)
    => HasLink (QueryParam sym v :> sub) where
    type MkLink (QueryParam sym v :> sub) = v -> MkLink sub
```

Shouldn't that be

``` haskell
type MkLink (QueryParam sym v :> sub) = Maybe v -> MkLink sub
```

We may very well want to link to the endpoint/page without specifying any value for a query param, which is not possible with the current instance.

### PR DESCRIPTION
**Pull request by alpmestan**
This can only go in 0.5 though, can't be cherry-picked in 0.4.

### CODE REVIEW

**Comment by alpmestan** [comment]
@jkarni care to review / merge? I would do it given how trivial the change is, but I prefer sticking to the policy whatever the size of the change is as long as it affects the code.

**Comment by jkarni** [comment]
Do MatrixParams require similar changes?

**Comment by jkarni** [comment]
And I guess this still needs a changelog entry

**Comment by alpmestan** [comment]
Oops, there you go =) Yes, Travis, please get back to work.

**Comment by alpmestan** [comment]
Good to merge? I'll update the changelogs right before the minor bugfix release, and update the ones for the 0.5 branch as well.

**Comment by jkarni** [comment]
Yup!

**Pull request merged**
