### PR TITLE
Use MonadThrow instead of Either in the signature of parseBaseUrl

### PR DESCRIPTION
**Pull request by PierreR**
See #80

### CODE REVIEW

**Comment by PierreR** [comment]
I have overlooked the tests. So I will need to fix that.

**Comment by jkarni** [comment]
I like the change, but as it stands it would be backwards incompatible. Can we maybe DEPRECATE the old `parseBaseUrl` and have the new one have a different name? (Unfortunately, I can't think of anything that's as good as `parseBaseUrl`...)

**Comment by soenkehahn** [comment]
I would consider keeping the name and force people to manually migrate. They will get a type error that is more or less easy to fix, right?

**Comment by jkarni** [comment]
But that means another major release (for something that seems quite minor).

**Comment by soenkehahn** [comment]
I personally don't see that as a big downside. At least pre `1.*` releases.

**Comment by soenkehahn** [comment]
Or more generally I don't see bumping the second digit in the version for something minor as a problem.

**Comment by PierreR** [comment]
> Unfortunately, I can't think of anything that's as good as parseBaseUrl...
Me neither ... Here are some ideas:
* parseUrl (if users are not expected to use both `http-client` and `servant-client)
* toBaseUrl
* fromString

Personally  I would force people to manually migrate, bump a major release but include this change in a global set of changes that allow users to move away from EitherT completely ...

**Comment by christian-marie** [comment]
I've already switched to Network.URI in the safe link code, I'd like to move this across to Network.URI here too to remove duplication if everyone's OK with that.

For a release tomorrow, though, let's just make a decision on this. I don't personally want to break peoples builds. So I'd prefer to deprecate or do major releases quickly. I don't see a problem with going to 0.5 for this release. People are free to bump their majors and be pleasantly surprised that nothing has actually broken.

As for the function name if we wish to ship two functions that do the same thing that are very similar (which I'm dubious about):

parseUrl may or may not be better, I'd like to deprecate the BaseUrl type and use Network.URI directly. Hence it's going to have its type change but not its name. This makes me vote no.

toBaseUrl seems good, fromString isn't partial though. That said, I think we can combine the best of these two with:

```haskell
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE OverloadedStrings #-}

import Network.URI
import Data.String
import Control.Monad.Catch

newtype ToBaseUrl = ToBaseUrl { toBaseUrl :: forall m. MonadThrow m => m URI }

instance IsString ToBaseUrl where
    fromString _ = 
        ToBaseUrl (throwM $ userError "catch!")

main :: IO ()
main = do
    print (toBaseUrl "http://ponies.io" :: Maybe URI)
    toBaseUrl "http://ponies.io" >>= print
```

Or just

**Comment by christian-marie** [comment]
Wrong button.

**Comment by PierreR** [comment]
I have just add another tiny (and orthogonal) change (the exception instance for ServantError) that I wish to be considered if there is a new `0.5` release.

Cheers

**Comment by christian-marie** [comment]
If there is a 0.5 release it is likely that it will not be this week. Is there anything in your PR that you require on hackage in the near future? If not, I see no reason we can't do this PR properly and break all of the things via a major release.

That is, if you agree that breaking changes are going to clean up the code base/remove duplicate code.

**Comment by PierreR** [comment]
No I am not in a hurry.

Exceptions/error handling is an important topic so I would proceed with care. There is #91 (if it is the way to go) that I believe should be part of `0.5`as well.

**Comment by tvh** [comment]
I don't really like the idea of reusing an exception from `http-client`. This would just make #51 harder.

**Comment by PierreR** [comment]
@tvh I see your point. I have used it because `http-client` is already a dependencies but you're right we don't need such a "complicated" data type.

**Comment by alpmestan** [comment]
To be honest, I don't feel strong about this PR since I *very* rarely use *servant-client*. It's however great that we're little by little polishing many dirty corners of servant, whatever the final solution ends up being. :+1:

**Comment by jkarni** [comment]
@christian-marie agreed that we should try to expose as little as possible of `http-client`.
Has no one yet written an `http-client-compat` package for GHCJS?

**Comment by PierreR** [comment]
I have made a couple changes as suggested. There is a new type "InvalidBaseUrlException" which is isomorphic to String. I only expose the type. Is that OK ?

Travis CI is saying that the build is on Error but it passes on ghc 7.10 and fails for unknown reason on ghc 7.8. I don't know why Travis is so unstable ...

**Comment by alpmestan** [comment]
I've just restarted the build, maybe it's just Travis timing out.

**Comment by PierreR** [comment]
A litlle question: I use `newtype` to define `InvalidBaseUrlException" but maybe I should use `data` instead.?

**Comment by PierreR** [comment]
Tests now pass for both ghc version.

**Comment by jkarni** [comment]
Thanks!

**Comment by arianvp** [comment]
#245 actually shows the tests fail for this change because servant-client's test suite wasn't running properly.

**Pull request merged**
