### PR TITLE
Test Hackage breakage

### PR DESCRIPTION
**Pull request by sol**

### CODE REVIEW

**Comment by sol** [comment]
This is mainly to experiment with a new [`zalora/tinc`](https://github.com/zalora/tinc feature).

Don't merge yet!

**Comment by jkarni** [comment]
neat!

**Comment by dredozubov** [comment]
@sol can you elaborate a bit more? Is it supposed to cache shared(between packages) extra-dependencies with stack or am i misunderstanding this?

**Comment by sol** [comment]
@dredozubov Kind of, but it does not use `stack`.  It uses [`zalora/tinc`](https://github.com/zalora/tinc) for dependency caching and also tests Hackage breakage.

**Comment by sol** [comment]
@jkarni From my perspective this is good for production now.  Currently I test against the latest versions on Hackage with GHC 7.8.4 and 7.10.2.  It's even faster than our current `stack`-based setup.

In addition we could test against Stackage.  If you people are interested in using `tinc` on travis I'm happy to add this.

**Comment by jkarni** [comment]
Will this use the latest versions of packages even if the cache already has an acceptable one?

**Comment by sol** [comment]
Yes.

You may want to have a look at the tinc READ ME.

**Comment by jkarni** [comment]
Perfect! This is exactly what we need!

**Comment by sol** [comment]
You may want to hit the rebuild button on Travis to populate the cache. The slowest build wins, so dependencies for 7.8.4 should already be cached. With the next build 7.10.2 will take longer and "win" when uploading the cache.

BTW, I had to disable -Werror due to aeson-0.10.* issues...

**Pull request merged**
