### PR TITLE
quick chat example base on chat example from engine-io

### PR DESCRIPTION
**Pull request by codedmart**

### CODE REVIEW

**Comment by codedmart** [comment]
@alpmestan @jkarni I will look at the failure tomorrow.

**Comment by alpmestan** [comment]
Sweet, thanks! It's amazing, I'll try and run it on my laptop tomorrow to see this all in action.

**Comment by codedmart** [comment]
@alpmestan @jkarni I will fix this in the morning.

**Comment by alpmestan** [comment]
Thanks!

**Pull request merged**
