### PR TITLE
Replace functionName with an array, and use functionRenamer to build …

### PR DESCRIPTION
**Pull request by freezeboy**
…the real function name

### CODE REVIEW

**Comment by freezeboy** [comment]
In order to resolve the conflicts I would also suggest to add in the instance for Capture, to add some "By{Capture}"

For instance:
```haskell
data MyAPI = "users" :> GET ...
                :<|> "users" :> Cap "id" Int :> GET
````
would generate (with camelcase)
```javascript
  var getUsers;
  var getUsersById;
```

And even maybe:
```haskell
data MyAPI = "groups" :> Cap "id" Int :> "users" :> Cap "name" Int :> GET
````
This ?
```javascript
  var getGroupsByIdUsersByName;
```

**Comment by freezeboy** [comment]
Could someone with the permission restart the travis test because I don't see the reason why it failed

**Comment by alpmestan** [comment]
Wouldn't we want to make the `camelCaseRenamer` the default one? That's, I'd say, the most commonly used convention. I'm also wondering we could find a better word than "renamer" -- since it doesn't actually "rename" but barely *puts the pieces of the name together*.

Aside from these two points, looks good to me!

**Comment by freezeboy** [comment]
I vote for CamelCase by default, I let you find a better name for the Renamer part

**Comment by codedmart** [comment]
@alpmestan @freezeboy Why not `concatCase` `snakeCase` `camelCase` just drop renamer? camelCase for sure.

**Comment by alpmestan** [comment]
@codedmart Sounds good to me. @freezeboy ?

**Comment by freezeboy** [comment]
very smart solution :)

**Comment by freezeboy** [comment]
Fixes #143

**Comment by alpmestan** [comment]
Great, thanks (again)! =)

**Pull request merged**
