### PR TITLE
Allow newer versions of base, template-haskell, lens, & unliftio-core

### LINKED ISSUE #1295: Support GHC 8.10
Right now there's a base <4.14 constraint in the .cabal files, while GHC 8.10 comes with base 4.14.

### PR DESCRIPTION
**Pull request by LeifW**
To allow building on GHC 8.10.1
Fixes #1295

### CODE REVIEW

**Comment by LeifW** [comment]
Kind of a dependency cycle, here - the cookbook stuff depends on servant libs in other repos, which in turn depend on servant...

**Comment by felixmulder** [comment]
I'm not entirely sure how cabal resolves this conflict, if we are in and building `servant` v0.17 - does it pick that one or the one from hackage?

If it picks the one we're currently in, then I think the patch to relax the version bounds on `servant-multipart` is enough to progress. Otherwise, I guess it's easiest to disable cookbook building, publish a new version of servant and then re-enable with an updated `servant-multipart`.

**Comment by felixmulder** [comment]
It seems that id _does_ work, I have cloned your branch and added the following commit:

https://github.com/felixmulder/servant/commit/1ad49c471bf9f5361dcb860a361be025f8569e18

Feel free to cherry-pick it, let's get this onto 8.10! :clap:

**Comment by felixmulder** [comment]
Confirmed that the changes pass CI! :tada:

https://github.com/felixmulder/servant/pull/1

**Comment by SamuelSchlesinger** [comment]
It seems @felixmulder's changes are sufficient to merge. What is blocking this merging? If I can be of some help, I would

**Comment by arianvp** [comment]
Thanks for the bump. @fisx let's have a look at this Monday?

**Comment by TomMD** [comment]
Anything I can do to get this moving?

**Comment by fisx** [comment]
> Anything I can do to get this moving?

I have no context whatsoever, but yes, @arianvp, let's find time to fix this next week!

@TomMD pestering us every couple of days may help :-)  (I'm not being sarkastic!)

Also, if you have any suggestions how to make CI pass, that may be useful.

**Comment by TomMD** [comment]
The failure appears to be due to a lens constraint on the version of template haskell.  The old lens version is being used because of a few `servant-*` pacakges.  When I `cabal build all` I can get it to build with the following diff on top of LeifW's:

```
diff --git a/cabal.project b/cabal.project
index 295938f1..f74d35b3 100644
--- a/cabal.project
+++ b/cabal.project
@@ -6,6 +6,9 @@ packages:
   servant-docs/
   servant-foreign/
   servant-server/
+  servant-quickcheck/
+  servant-multipart/
+  servant-js/
   doc/tutorial/
 
 -- servant streaming
diff --git a/servant-client-core/servant-client-core.cabal b/servant-client-core/servant-client-core.cabal
index b09517fa..53a8fbf7 100644
--- a/servant-client-core/servant-client-core.cabal
+++ b/servant-client-core/servant-client-core.cabal
@@ -74,7 +74,7 @@ library
   -- Other dependencies: Lower bound around what is in the latest Stackage LTS.
   -- Here can be exceptions if we really need features from the newer versions.
   build-depends:
-      aeson                 >= 1.4.1.0  && < 1.5
+      aeson                 >= 1.4.1.0  && < 1.6
     , base-compat           >= 0.10.5   && < 0.12
     , base64-bytestring     >= 1.0.0.1  && < 1.1
     , exceptions            >= 0.10.0   && < 0.11
diff --git a/servant-docs/servant-docs.cabal b/servant-docs/servant-docs.cabal
index 07cfb73f..84f1a539 100644
--- a/servant-docs/servant-docs.cabal
+++ b/servant-docs/servant-docs.cabal
@@ -57,7 +57,7 @@ library
   -- Other dependencies: Lower bound around what is in the latest Stackage LTS.
   -- Here can be exceptions if we really need features from the newer versions.
   build-depends:
-      aeson                >= 1.4.1.0  && < 1.5
+      aeson                >= 1.4.1.0  && < 1.6
     , aeson-pretty         >= 0.8.5    && < 0.9
     , base-compat          >= 0.10.5   && < 0.12
     , case-insensitive     >= 1.2.0.11 && < 1.3
diff --git a/servant/servant.cabal b/servant/servant.cabal
index 99d702b4..d3a93b01 100644
--- a/servant/servant.cabal
+++ b/servant/servant.cabal
@@ -96,7 +96,7 @@ library
   -- Here can be exceptions if we really need features from the newer versions.
   build-depends:
       base-compat            >= 0.10.5   && < 0.12
-    , aeson                  >= 1.4.1.0  && < 1.5
+    , aeson                  >= 1.4.1.0  && < 1.6
     , attoparsec             >= 0.13.2.2 && < 0.14
     , bifunctors             >= 5.5.3    && < 5.6
     , case-insensitive       >= 1.2.0.11 && < 1.3
```

And in the servant-* packages we have...

servant-js:

```
diff --git a/servant-js.cabal b/servant-js.cabal
index a2d72fd..47e74f5 100644
--- a/servant-js.cabal
+++ b/servant-js.cabal
@@ -50,10 +50,10 @@ library
                        Servant.JS.Internal
                        Servant.JS.JQuery
                        Servant.JS.Vanilla
-  build-depends:       base            >= 4.9     && <4.14
+  build-depends:       base            >= 4.9     && <4.15
                      , base-compat     >= 0.10.5  && <0.12
                      , charset         >= 0.3.7.1 && <0.4
-                     , lens            >= 4.17    && <4.19
+                     , lens            >= 4.17    && <4.20
                      , servant-foreign >= 0.15    && <0.16
                      , servant         >= 0.15    && <0.18
                      , text            >= 1.2.3.0 && < 1.3
```

And the `servant-multipart`, `servant-quickcheck` are HEAD (hackage isn't uploaded yet).

**Comment by fisx** [comment]
I suppose we should release `servant-multipart`, `servant-quickcheck` first, then?

Thanks for all the help / sorry we're taking so long!

**Comment by fisx** [comment]
closed in favor of #1318 

i made releases on hackage for `servant-{js,multipart,quickcheck}`, now everything should be good to merge here, too.  Let's see what travis thinks.

**Pull request closed without merging**
