### PR TITLE
Support http-api-data-0.3

### PR DESCRIPTION
**Pull request by phadej**
Btw: @fizruk Why you shuffled the module names, from `Web.HttpApiData.Internal ` to `Web.Internal.HttpApiData`?

### CODE REVIEW

**Comment by jkarni** [comment]
Wow that was quick! Thanks!

The new version contains the FormUrlEncoded classes that are also still here (see #348). We should remove them (conditionally on http-api-data version?). But I'm +1 on merging first.

**Comment by phadej** [comment]
I'm :-1: on conditional API. If `FormUrlEncoded` are provided by `http-api-data-0.3` then we should bump lower bound on it.

I'd rather make a PRs for [other packages using `http-api-data`](http://packdeps.haskellers.com/reverse/http-api-data), there aren't that many. `persistent` is upgraded already it seems.

**Comment by jkarni** [comment]
@phadej I made changes to replace our `FormUrlEncoded` versions with the new `http-api-data` ones on top of this PR in #582.

**Comment by fizruk** [comment]
@phadej I shuffled internal module so that both internal modules are grouped under `Web.Internal`. No major reason. But you shouldn't import `Internal` modules, those functions are available at `Web.HttpApiData` already (and have been for a few past releases).

**Comment by jkarni** [comment]
Can I merge?

**Comment by phadej** [comment]
Superseded by https://github.com/haskell-servant/servant/pull/582

**Pull request closed without merging**
