### PR TITLE
Relax version bounds to build with ghc 8.2.1

### PR DESCRIPTION
**Pull request by albertov**

### CODE REVIEW

**Comment by alpmestan** [comment]
LGTM. @phadej ?

**Comment by albertov** [comment]
Will try to add a stanza to `.travis.yml` as soon as stack releases an LTS targeting 8.2

**Comment by phadej** [comment]
LTS won't happen soon. AFAIK you can use release-candidates in stack, but I don't remember how by heart. IIRC there was something in reddit thread

**Comment by phadej** [comment]
https://www.reddit.com/r/haskell/comments/6bqfk9/testing_ghc_release_candidates_with_stack/

**Comment by albertov** [comment]
Thanks for the pointer. I'll see if I have some time to learn this some day after I finish updating the rest of the dependencies I need to update to get our apps building with ghc 8.2.1. Meanwhile, if someone wan't to beat me to it do not hesitate to do it :)

**Comment by phadej** [comment]
superseded by #764

**Pull request closed without merging**
