### PR TITLE
add README for release process

### PR DESCRIPTION
**Pull request by soenkehahn**

### CODE REVIEW

**Comment by alpmestan** [comment]
LGTM.

**Comment by arianvp** [comment]
LGTM.

**Comment by rvion** [comment]
You wrote `./scripts/bump-version.sh` but the script name is `./scripts/bump-versions.sh`(with an 's' at the end)

also, I just wanted to mention the existence of 
```haskell 
stack sdist $(pwd) --pvp-bounds both
```
The command create source distribution tarballs and generated pvp-bounds automatically
(some ref pvp-bounds option [here](https://www.fpcomplete.com/blog/2015/09/stack-pvp) and [here](https://readthedocs.org//search/?q=pvp-bounds&check_keywords=yes&area=default&project=stack&version=stable&type=file)

**Comment by soenkehahn** [comment]
Thanks for reviewing.

@rvion: Good catch.

**Pull request merged**
