### PR TITLE
Authentication: Digest auth support

### PR DESCRIPTION
**Pull request by arianvp**
This is based off of aaronlevin's pull request. It adds (minimal) support for  Digest authentication.

Any comments are welcome. I still need to write tests and `HasClient` instances. But I'm awaiting aaronlevin's  `HasClient` impl for `BasicAuth` to see how to do that.

### CODE REVIEW

**Comment by aaronlevin** [comment]
@arianvp I've implemented `HasClient` on my branch. also, you might want to rebase off my branch again as I've resolved some merge conflicts from master.

**Comment by arianvp** [comment]
Is it okay if I remove this pull request? It's probably easier to have all the auth stuff in one pull

**Comment by alpmestan** [comment]
Sure, whatever is handier.

**Comment by arianvp** [comment]
I think we can close this PR (for now) as Digest doesn't seem used a lot and other authentication schemes are better suited.   Basic-auth over HTTPS gives more benefits than Digesy.

**Pull request closed without merging**
