### PR TITLE
Allow GHC 8.4.1

### PR DESCRIPTION
**Pull request by jkarni**
And include it in the travis build matrix.
    Also includes fixes for a couple of typos and copyright dates in
    cabal files.

### CODE REVIEW

**Comment by jkarni** [comment]
There blaze-builder [doesn't support GHC 8.4.1 yet](https://github.com/lpsmith/blaze-builder/issues/15). Let's rerun when the linked issue is fixed.

**Comment by DanBurton** [comment]
Note that `blaze-builder-0.4.1.0` has been released, which does support ghc 8.4.1.

**Comment by jkarni** [comment]
@DanBurton thanks! 

Looks like now it's `postgresql-simple` that still needs to bump its `base` upper bound

**Comment by phadej** [comment]
This looks good. See `servant-foreign` change in #925 

Note we are also blocked on https://github.com/zmthy/http-media/pull/25

**Comment by alpmestan** [comment]
Are we still blocked on other things?

**Comment by phadej** [comment]
https://github.com/lpsmith/postgresql-simple/issues/252

**Comment by phadej** [comment]
`master` has GHC-8.4.3 in travis now. Sorry it took so long :/

**Pull request closed without merging**
