### PR TITLE
Release servant-0.20.2 and sister libraries

### PR DESCRIPTION
**Pull request by ysangkok**
Planning to release this on wednesday if I have maintainer permissions on Hackage by then.

### CODE REVIEW

**Comment by ysangkok** [comment]
@tchoutri I am still missing Hackage maintainer privileges on:

* servant-[auth-client](https://hackage.haskell.org/package/servant-auth-client)
* servant-[auth-docs](https://hackage.haskell.org/package/servant-auth-docs)
* servant-[auth-server](https://hackage.haskell.org/package/servant-auth-server)
* servant-[foreign](https://hackage.haskell.org/package/servant-foreign)
* servant-[http-streams](https://hackage.haskell.org/package/servant-http-streams)
* servant-[machines](https://hackage.haskell.org/package/servant-machines)
* servant-[pipes](https://hackage.haskell.org/package/servant-pipes)
* servant-[swagger](https://hackage.haskell.org/package/servant-swagger)

**Comment by tchoutri** [comment]
Yep I'll be on it tomorrow, thanks :)

**Comment by tchoutri** [comment]
@ysangkok Permissions granted! Sorry for the delay!

**Comment by ysangkok** [comment]
@tchoutri Forgot a couple of packages:
* https://hackage.haskell.org/package/servant-auth
* https://hackage.haskell.org/package/servant-auth-swagger

I'll upload the servant-auth and servant-auth-{server,client,docs,swagger} when you add me to those two. Because of the minimum bounds it doesn't make sense to upload e.g. client before servant-auth has been updated.

The other ones have been updated already.

**Comment by tchoutri** [comment]
@ysangkok Permissions granted on those two :+1:

**Pull request merged**
