### PR TITLE
include Authentication.lhs in tutorial project and table of contents

### PR DESCRIPTION
**Pull request by alpmestan**
@aaronlevin it seems the CI is failing on the tutorial code, would you mind taking a look when you get a chance to? so that we can publish your very own section of the tutorial :)

### CODE REVIEW

**Comment by aaronlevin** [comment]
I'll take a look tonight or tomorrow! Sorry about this.

**Comment by alpmestan** [comment]
No worries, but given that people are asking about auth examples at least once a day on IRC, I thought it'd be nice to get your bit of the tutorial up officially as well =)

**Comment by aaronlevin** [comment]
@alpmestan should compile now. permission to merge?

**Comment by alpmestan** [comment]
Yup! Go ahead.

**Pull request merged**
