### PR TITLE
Allow newer hashable, lens, text

### PR DESCRIPTION
**Pull request by ysangkok**
Tested using

    cabal test --constraint='hashable>=1.4' --constraint='text>=2' --constraint='lens>=5.1' --allow-newer=servant-multipart:lens,servant-multipart:text,servant-pagination:text,io-streams:text,blaze-html:text,swagger2:text,servant-js:lens,servant-js:text all

on GHC 9.0.2.

### CODE REVIEW

**Review by tchoutri — APPROVED** [review]

**Review by akhesaCaro — APPROVED** [review]
LGTM if the CI agrees :p

**Review by alpmestan — APPROVED** [review]
LGTM. We'll probably want to reflect these changes as revisions to the last releases of all the affected libraries as well.

**Comment by gdeest** [comment]
> LGTM. We'll probably want to reflect these changes as revisions to the last releases of all the affected libraries as well.

Agreed.

**Comment by ysangkok** [comment]
@alpmestan It seems like the revisions you refer to haven't actually been made. Do you know who I can ping to get them out?

**Pull request merged**
