### PR TITLE
Group notes together

### PR DESCRIPTION
**Pull request by ivan-m**

### CODE REVIEW

**Comment by ivan-m** [comment]
I ended up choosing option 3 as it allows the end-user to choose what the points are for (more documentation on the purpose of the endpoint? description of the types involved? etc.)

**Comment by alpmestan** [comment]
So this is the final changeset you're suggesting to address the whole situation about notes, right?

**Comment by ivan-m** [comment]
Yes

**Comment by alpmestan** [comment]
Looks good to me. Keep going like this and you'll end up as servant-docs care-taker =)

**Comment by ivan-m** [comment]
> you'll end up as servant-docs care-taker

Are you trying to scare me? :p

**Comment by alpmestan** [comment]
I am.

**Comment by alpmestan** [comment]
More seriously, it could probably benefit from having someone who uses it regularly and possibly in non trivial ways. It's been quite stable (not to say inactive) for a while, and maybe it could become as useful as the swagger UI or something with a little bit of love. Maybe.

**Pull request merged**
