### PR TITLE
Add AddSetCookies instance for when the left tree is the same before and after the transformation

### PR DESCRIPTION
**Pull request by ohri-anurag**
Adding code suggested by @mastarija on issue #1601

### CODE REVIEW

**Comment by ohri-anurag** [comment]
The CI fails here, but this is what I did on my machine:
1. Modified this line in `shell.nix`:
```diff
-      buildInputs = [ ghc zlib python3 wget cabal-install postgresql openssl stack haskellPackages.hspec-discover ]
+      buildInputs = [ ghc zlib python3 wget cabal-install postgresql openssl stack haskellPackages.hspec-discover haskellPackages.doctest ]
```
2. Ran this command: `nix-shell nix/shell.nix --argstr compiler ghc865Binary`
3. Both `cabal build all` and `cabal test all` passed in the shell entered at step 2.
4. I have also tested this with ghc 9.0.1, without any changes to `shell.nix`, it works.

**Comment by ysangkok** [comment]
Could you please rebase on `master`?

**Comment by ysangkok** [comment]
I don't think this rebase was done right, since some commits from the master branch are shown here.

**Comment by ohri-anurag** [comment]
Closed in favor of #1702

**Pull request closed without merging**
