### PR TITLE
Support GHC 9.10.1

### PR DESCRIPTION
**Pull request by tchoutri**
Dependent on:
  * https://github.com/HeinrichApfelmus/vault/pull/41
  * https://github.com/haskell-unordered-containers/unordered-containers/pull/490
  * https://github.com/haskellari/postgresql-simple/issues/139
    * Needs `cabal-install` 3.12: https://github.com/haskell/cabal/issues/9885

### CODE REVIEW

**Comment by maksbotan** [comment]
@tchoutri AFAIU this is work in progress?

**Comment by tchoutri** [comment]
@maksbotan yes we're still blocked on the two linked PRs.

**Comment by tchoutri** [comment]
@maksbotan I'm updating the description with ever new blocker I find

**Comment by ysangkok** [comment]
I merged #1765 so I think this can be closed.

**Pull request closed without merging**
