### PR TITLE
Adding instances for non-JSON content types to `servant-foreign`

### PR DESCRIPTION
**Pull request by phadej**
Rebase of #832

### CODE REVIEW

**Comment by phadej** [comment]
- Now as I review this, I see that we generate foreign stuff also for non-JSON endpoints
- thus e.g. `servant-js` in current form will generate functions for non-JSON endpoints
- That would be simple fix to generate functions only for JSON endpoints
- but then we won't get **compile-time error**, if we forget `JSON` from some endpoint.

For me this sounds like a blocker. ping @jkarni.

**Comment by phadej** [comment]
I'd postpone this from `0.12` preparations for now.

**Comment by alpmestan** [comment]
We could quite simply make the JS stuffs available only if the endpoints all support JSON requests/responses, and give a custom type error otherwise?

**Comment by exarkun** [comment]
I am interested in this change.  How can I help?

**Comment by phadej** [comment]
https://github.com/haskell-servant/servant/pull/848#issuecomment-342126375 needs a solution

**Comment by cdupont** [comment]
Hello, I hit this problem. Is there a solution? Thanks!

**Pull request closed without merging**
