### PR TITLE
Use parseRequest

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by arianvp** [comment]
Looks good. LGTM

**Comment by soenkehahn** [comment]
Ah, yes, makes sense.

I'd prefer `parseRequest` to be a top-level declaration with a type signature. Apart from that LGTM.

**Comment by phadej** [comment]
Amended `parseRequest` to be top-level

**Comment by soenkehahn** [comment]
@phadej: Nice, thanks a lot!

**Comment by soenkehahn** [comment]
Rebased and merged: https://github.com/haskell-servant/servant/commit/197ed0548a0e6a5b6fcf7f9926b7a041ffd4b97f

**Pull request closed without merging**
