### PR TITLE
scripts: install all of the servant ecosystem at once, for consistent dependencies

### PR DESCRIPTION
**Pull request by christian-marie**
Let's see if this travises...

### CODE REVIEW

**Comment by christian-marie** [comment]
How do I shot doctest on 7.8.4?

**Comment by jkarni** [comment]
Thanks!
 I don't really know what's going on with doctest. I'll have a look later today

**Comment by soenkehahn** [comment]
Here's a fix for the doctest issue: #79.

**Comment by christian-marie** [comment]
I think this is OK.

**Pull request merged**
