### PR TITLE
Fixed javascript for tutorial/T9

### PR DESCRIPTION
**Pull request by sguy**

### CODE REVIEW

**Comment by alpmestan** [comment]
Are those names the one generated with *servant-js* currently? If yes I'll merge this PR. Since we've done quite a few changes in *servant-js* with @freezeboy, this subtle problem might have gone unnoticed indeed.

**Comment by sguy** [comment]
Yes.  I was working through the tutorial last night and I had to make this
case change to get everything to work.

**Comment by alpmestan** [comment]
Merged, thanks!

**Comment by freezeboy** [comment]
You simply mean the api.js was not up to date ?
It's possible, as it is generated by the runtime I may have forgotten to commit it.
other .js files may have the same problem (and I won't have access to my ssh key until next week, so feel free to add them).

**Comment by alpmestan** [comment]
No it's just that there's been a subtle change in the function names as we generate them by default, so the Javascript code that uses it in the tutorial had to be updated.

**Pull request merged**
