### PR TITLE
cookbook sentry integration page

### PR DESCRIPTION
**Pull request by marcosh**
Following what I wrote [here](http://marcosh.github.io/post/2018/06/21/sentry-servant.html), as suggested by @alpmestan, I added a new page to the cookbook describing how to integrate Sentry as a mean to collect runtime errors

### CODE REVIEW

**Comment by phadej** [comment]
I (as release manager) would prefer changelog not touched during development. It's simpler for me to assemble it during release preparations, than to wonder what's there and what's not. Also I sometimes merge multiple related contributions into single entry. Also to avoid unnecessary merge conflicts. Having a good description in PR (to be used as the entry) would help to though.

I also want to include all PRs into changelog, to mention all contributions. Cookbook entries are specially important as they are appreciated doc PRs.

If that sounds good to everyone, I'll amend contributions.md

**Comment by alpmestan** [comment]
OK, let's go with these guidelines (re cookbook entries -- the don't-update-changelog policy was already in place I think).

**Comment by marcosh** [comment]
Allright, changelog entry removed

**Comment by alpmestan** [comment]
I'm sorry, I completely forgot about this. Any chance you could rebase this PR or should I?

**Comment by marcosh** [comment]
no worries

I just rebased on master, hope everything is fine

**Comment by alpmestan** [comment]
Thanks a lot, @marcosh!

**Pull request merged**
