### PR TITLE
for discussion only

### PR DESCRIPTION
**Pull request by mwotton**
I've had a bit of trouble working out how to use the new general authentication
framework on anything but trivial examples, so I thought it might make sense to
provide a simple example & a failing test of how I would expect to be able to
use it in the hope that someone can point out a flaw in my thinking.

### CODE REVIEW

**Comment by mwotton** [comment]
thanks to @aaronlevin who's been helping me work through this.

**Comment by jkarni** [comment]
I don't entirely understand what's happening here. Why is this test failing? And what more generally is the pattern?

**Comment by mwotton** [comment]
I'm trying to work out how to protect an entire route with the new
authentication system. It works OK if I protect each :<|> branch
individually, but I can't work out how to do it at the top level and still
unpack the individual routes as API functions.

**Comment by mwotton** [comment]
Entire app, I mean.

**Comment by mwotton** [comment]
So, this makes it work :) may be worth leaving in as an example, I bashed my head against it for a while trying to work out how to get it working.

**Comment by alpmestan** [comment]
It definitely can't hurt to leave it around or include something along those lines in the tutorial, or both!

**Comment by soenkehahn** [comment]
I agree with @alpmestan, that ideally we'd have some better documentation about this, but this should happen in another PR.

Can we close this?

**Comment by mwotton** [comment]
@soenkehahn yep, kill it with fire (but a flagship project showing use of the api would be extra-fantastic).

**Pull request closed without merging**
