### PR TITLE
fix stack.yaml

### PR DESCRIPTION
**Pull request by soenkehahn**

### CODE REVIEW

**Comment by soenkehahn** [comment]
Btw, this will revert `aeson` to `0.9`. Is there a good reason to diverge from what stackage does?

**Comment by jkarni** [comment]
The original reason for 0.11 was that the tutorial (IIRC) needed some instance from it. But adding it to the stack file alone (without putting a version bound in the tutorial's cabal file) was the wrong thing to do...

**Comment by soenkehahn** [comment]
Well, the tutorial at least compiles with `0.9`...

**Comment by jkarni** [comment]
Then by all means!

**Comment by jkarni** [comment]
@haskell-servant/maintainers can we merge?

**Comment by alpmestan** [comment]
👍

**Comment by arianvp** [comment]
:+1:

**Comment by Tehnix** [comment]
With #520 and #521 merged, the `stack.yaml` update is not needed anymore - I've no idea about the rest though.

**Comment by soenkehahn** [comment]
@Tehnix: Yes, some of the changes were obsolete. Just rebased.

**Pull request merged**
