### PR TITLE
Pass in Manager as argument to 'client'

### LINKED ISSUE #176: Client functions with Manager param
I'd like to open a discussion for allowing custom connection manager for servant-client. Currently there is an [internal global manager](https://github.com/haskell-servant/servant/blob/master/servant-client/src/Servant/Common/Req.hs#L133) established via unsafePerformIO which is used for everything. My guess it's for convenience. I'd like to propose at least allowing to specify Manager for `client` function, but would be even better to be able to specify it per function as #174 asks for BaseUrl.

### PR DESCRIPTION
**Pull request by jkarni**
Fixed #176 .

### CODE REVIEW

**Comment by jkarni** [comment]
Don't have much patience to pattern match twice on client functions, so I went with `unsaferPerformIO` in the examples. Of dubious pedagogical value, but no different than what we were doing before.

**Comment by alpmestan** [comment]
Well, at least it will now be obvious that it is the "easy but dirty" way, and give the flexibility to do things in a cleaner, more configurable way. This does give us client-function debugging as well right by tweaking the `Manager` (to print the request whenever it sends one), right?

**Comment by alpmestan** [comment]
The tutorial will need to be updated for this, btw.

**Comment by jkarni** [comment]
I'll keep a list of things I know have to be updated for the tutorial (doing so now would be confusing).

**Comment by zudov** [comment]
:100

**Pull request merged**
