### PR TITLE
Generalized Auth Support

### PR DESCRIPTION
**Pull request by aaronlevin**
This pull request takes the generalized auth support fom https://github.com/haskell-servant/servant/pull/341. This includes:

- `AuthProtected` API type.
- `AuthServerData` type family to specify what data type the server receives when protected.
- `AuthClientData` type family to specify what data type the client requires to authenticate a request.
- `AuthHandler` data type that wraps methods required for the `Config` mechanism.

This PR will allow API authors to create ad-hoc authentication mechanisms.

Some notes:
- `servant-docs` support is not included in this PR. It is assumed the `servant-docs` support included in the `auth-basic`.

### CODE REVIEW

**Comment by aaronlevin** [comment]
Rebased onto `master`. I am also working on pushing some of this into an `Experimental` module but am running into Orphan instance issues.

**Comment by aaronlevin** [comment]
@soenkehahn @alpmestan @arianvp @fizruk I moved the generalized auth stuff to an experimental module in each subproject. It'd be great to get a thumbs up or down on this. It's been a long and arduous journey I know! :) :ghost: :smile_cat:

**Comment by alpmestan** [comment]
Aside from the minor comment I made, LGTM. Just a bid sad that we add `UndecidableInstances` in a module that's imported by all users instead of having it live in an `Experimental` module that we opt-in for explicitly.

**Comment by aaronlevin** [comment]
@alpmestan so, perhaps I"m doing something wrong, but I tried to define the `HasServer` instances in `Servant.Server.Experimental.Auth` and my tests wouldn't compile (I tried to import specifically the instances via `Servant.Server.Expeirmental.Auth()` and that still didn't work).

Any tips for orphan `HasServer` instances?

**Comment by aaronlevin** [comment]
@alpmestan good news! I was able to move the instance into the `Experimental` module and remove the `UndecidableInstances` extension from the `HasServer` stuff. Now you need to explicitly include `Servant.Server.Experimental.Auth` to get that instance.

Also, I moved `Servant.Experimental` to `Servant.API.Experimental`. Once this passes tests, can I merge?

**Comment by alpmestan** [comment]
Great. Makes me feel more comfortable =)

Once the CI is green, I do think it's time for servant to get some nice _auth_ support :+1:

**Comment by soenkehahn** [comment]
Would you consider squashing (some of) the commits? I haven't looked at them in detail, but some of them (e.g. renamings) don't seem to be useful commits to have in the git history.

**Comment by aaronlevin** [comment]
@soenkehahn sure. I will squash before merging.

**Comment by soenkehahn** [comment]
Thanks a lot!

**Comment by rvion** [comment]
Yay, thanks !

**Pull request merged**
